const wordSentence = {
  "Forebode": "Dark clouds forebode an incoming storm.",
  "Foreshadow": "The eerie silence foreshadowed the tragic news.",
  "Ominous": "The ominous sound of thunder made the children uneasy.",
  "Premonition": "She had a premonition that the trip would go wrong.",
  "Warning": "The red flag was a warning of dangerous sea conditions.",
  "Daunting": "Climbing the mountain alone was a daunting task.",
  "Intimidate": "The opposing team tried to intimidate us with their size.",
  "Sinister": "A sinister smile crept across his face in the dark alley.",
  "Agile": "The gymnast was incredibly agile on the balance beam.",
  "Lithe": "Her lithe figure moved effortlessly across the dance floor.",
  "Supple": "The leather was soft and supple to the touch.",
  "Aesthetic": "The minimalist design had great aesthetic appeal.",
  "Comely": "The comely hostess welcomed us with a warm smile.",
  "Prodigy": "The child was a musical prodigy, composing symphonies at the age of eight.",
  "Precocious": "Her precocious ability in mathematics impressed all her teachers.",
  "Anticipate": "We anticipate heavy traffic during the holiday season.",
  "Forecast": "The weather forecast predicted rain all weekend.",
  "Foresight": "With remarkable foresight, she invested in tech stocks early.",
  "Foresee": "Economists foresee a rise in interest rates next quarter.",
  "Foretell": "The fortune teller foretold great success in his future.",
  "Presage": "Dark clouds often presage a storm.",
  "Prescience": "His prescience about market trends saved the company.",
  "Prognosis": "The doctor gave a positive prognosis after the surgery.",
  "Enrage": "The delay enrage the passengers stuck in the airport.",
  "Fume": "She began to fume silently after hearing the unfair decision.",
  "Incense": "The unfair treatment incensed the employees.",
  "Indignation": "He expressed indignation at the corruption in politics.",
  "Infuriate": "The rude comment infuriated her.",
  "Irate": "An irate customer demanded a refund.",
  "Ire": "The decision raised the ire of the public.",
  "Livid": "She was livid when she saw the broken vase.",
  "Wrath": "The villain faced the wrath of the hero.",
  "Intellectual": "He enjoyed deep intellectual discussions on philosophy.",
  "Cerebral": "The novel had a very cerebral tone, focusing on ideas.",
  "Erudite": "She impressed the panel with her erudite answers.",
  "Enlightened": "They adopted an enlightened approach to education reform.",
  "Enlightenment": "Meditation helped him reach a state of enlightenment.",
  "Pundit": "A political pundit commented on the election results.",
  "Refined": "Her manners were elegant and refined.",
  "Refinement": "The new version of the app showed great refinement.",
  "Adept": "She is adept at solving complex problems.",
  "Adroit": "The magician was adroit with his hands.",
  "Consummate": "He is a consummate professional in his field.",
  "Deft": "With a deft touch, he completed the painting.",
  "Dexterous": "Her dexterous fingers made quick work of the embroidery.",
  "Finesse": "She handled the negotiation with great finesse.",
  "Proficient": "He is proficient in three languages.",
  "Prowess": "The knight showed his prowess in battle.",
  "Inept Opposite": "His inept performance cost the team the match.",
  "Maladroit Opposite": "His maladroit attempt at fixing the sink made it worse.",
  "Turn": "She made a sharp turn at the corner.",
  "Complex": "The instructions were too complex to follow.",
  "Circuitous": "We took a circuitous route to avoid traffic.",
  "Convoluted": "His explanation was too convoluted to grasp.",
  "Complicated": "The relationship became complicated after that.",
  "Intertwined": "Their fates were deeply intertwined.",
  "Involved": "The plot was too involved to enjoy.",
  "Meander": "The river meanders through the valley.",
  "Tortuous": "The road to the village was long and tortuous.",
  "Affinity": "He has an affinity for classical music.",
  "Aptitude": "She has an aptitude for math.",
  "Bent": "He has a creative bent of mind.",
  "Disposed": "She felt disposed to help the needy.",
  "Penchant": "He has a penchant for spicy food.",
  "Predilection": "She has a predilection for dark chocolate.",
  "Predisposition": "He has a genetic predisposition to diabetes.",
  "Proclivity": "She has a proclivity for drama.",
  "Propensity": "He has a propensity to exaggerate.",
  "Futile": "It's futile to argue with him.",
  "Ineffectual": "His efforts were ineffectual.",
  "Efficacy": "The efficacy of the vaccine was proven.",
  "Feckless": "His feckless leadership failed the team.",
  "Shocking": "The news of the accident was shocking.",
  "Aghast": "She was aghast at the mess.",
  "Appalling": "The living conditions were appalling.",
  "Egregious": "It was an egregious error.",
  "Ghastly": "He looked ghastly after the illness.",
  "Gross": "That smell is gross!",
  "Gruesome": "The crime scene was gruesome.",
  "Heinous": "It was a heinous crime.",
  "Hideous": "That sculpture is hideous.",
  "Horrendous": "The cost of treatment was horrendous.",
  "Monstrous": "He committed monstrous acts.",
  "Morbid": "He had a morbid fascination with crime.",
  "Unsightly": "The graffiti was unsightly.",
  "Vile": "His comments were vile and offensive.",
  "Disjointed": "His argument was disjointed and hard to follow.",
  "Polarize": "The debate polarized the audience into two camps.",
  "Segregate": "The policy aimed to segregate students based on abilities.",
  "Connected": "The rooms are connected by a hallway.",
  "Nexus": "The city is a nexus for trade routes.",
  "Dodge": "He managed to dodge the question skillfully.",
  "Avert": "She averted her eyes during the scary scene.",
  "Circumvent": "They tried to circumvent the new tax law.",
  "Deflect": "He deflected the criticism with a joke.",
  "Elude": "The thief managed to elude the police.",
  "Elusive": "The solution to the problem remains elusive.",
  "Evade": "She evaded the question by changing the subject.",
  "Evasive": "He gave an evasive answer about the rumors.",
  "Shirk": "Don’t shirk your duties at work.",
  "Skirt": "He skirted the issue during the interview.",
  "Swerve": "She swerved to avoid hitting the deer.",
  "Head-on": "They had a head-on confrontation over the project.",
  "Inevitable": "A change in leadership was inevitable.",
  "Unavoidable": "Traffic delays were unavoidable after the storm.",
  "Clumsy": "He is clumsy and often knocks things over.",
  "Fumble": "She fumbled with her keys at the door.",
  "Gauche": "His gauche behavior made everyone uncomfortable.",
  "Gawky": "The teenager felt gawky and awkward.",
  "Ungainly": "The bird looked ungainly as it landed.",
  "Buoyant": "Despite the setback, she remained buoyant and cheerful.",
  "Sanguine": "He is sanguine about the company’s future.",
  "Upbeat": "She sounded upbeat despite the bad news.",
  "Waste time": "He tends to waste time on social media.",
  "Dilatory": "Her dilatory tactics frustrated the committee.",
  "Linger": "Don't linger after the meeting is over.",
  "Malinger": "He was caught malingering to avoid his shift.",
  "Didactic": "The novel had a didactic tone, teaching moral lessons.",
  "Pedantic": "His pedantic nature made conversations tedious.",
  "Sophist": "The sophist twisted logic to win the debate.",
  "Diffuse": "The fragrance diffused throughout the room.",
  "Disseminate": "The government aims to disseminate health information.",
  "Promulgate": "The law was promulgated last year.",
  "Propagate": "They propagate their beliefs through online platforms.",
  "Adulation": "The celebrity was uncomfortable with the constant adulation.",
  "Obsequious": "His obsequious behavior annoyed his colleagues.",
  "Sycophant": "The sycophant agreed with everything the boss said.",
  "Anatomical": "The diagram shows the anatomical structure of the heart.",
  "Corporeal": "Ghosts are believed to lack a corporeal form.",
  "Physiological": "Stress affects both mental and physiological health.",
  "Animosity": "There was evident animosity between the two rivals.",
  "Antipathy": "He felt a deep antipathy towards injustice.",
  "Aversion": "She has an aversion to spiders.",
  "Despicable": "Lying to gain sympathy is despicable behavior.",
  "Detest": "I detest cruelty of any kind.",
  "Loathe": "He loathes dishonesty.",
  "Repel": "The smell was enough to repel anyone.",
  "Repugnant": "His views on the issue are repugnant.",
  "Repulsion": "The sight of the spoiled food caused repulsion.",
  "Antiquated": "The machinery is antiquated and needs replacing.",
  "Archaic": "Some archaic laws are still in effect.",
  "Dated": "Her outfit looked dated in today's fashion.",
  "Obsolete": "That technology is now obsolete.",
  "Outmoded": "His ideas are outmoded and irrelevant.",
  "Quaint": "The town has a quaint charm.",
  "Outdated": "The data is outdated and needs updating.",
  "Chronicle": "He chronicled his travels in a blog.",
  "Chronological": "The story was told in chronological order.",
  "Contemporary": "She is a contemporary of the famous poet.",
  "Simultaneous": "The two events happened simultaneously.",
  "Erstwhile Opposite": "The erstwhile king now lives in exile.",
  "Anachronism Opposite": "A smartphone in a medieval setting is an anachronism.",
  "Careful": "She is always careful when crossing the road.",
  "Risky Opposite": "Investing without research is risky.",
  "Caveat": "The deal was good, but with a caveat.",
  "Circumspect": "He was circumspect in his business dealings.",
  "Heedful": "Be heedful of the warning signs.",
  "Prudent": "It’s prudent to save for emergencies.",
  "Wary": "Be wary of strangers offering help.",
  "Folly Opposite": "Spending recklessly is pure folly.",
  "Rash Opposite": "Don’t make rash decisions.",
  "Reckless Opposite": "Reckless driving endangers lives.",
  "Bask": "She basked in the praise after the presentation.",
  "Complacent": "He grew complacent after a few small victories.",
  "Admonish": "The teacher admonished the student for being late.",
  "Berate": "She berated him for forgetting their anniversary.",
  "Censure": "The official faced censure from his peers.",
  "Chastise": "The parent chastised the child for misbehaving.",
  "Rebuke": "He received a sharp rebuke for his actions.",
  "Reprimand": "The manager issued a formal reprimand.",
  "Reproach": "There was a tone of reproach in her voice.",
  "Upbraid": "The officer upbraided the cadet for negligence.",
  "Assail": "The editor was assailed by critics after publication.",
  "Castigate": "He was castigated for failing his duties.",
  "Decry": "Activists decried the unfair policy.",
  "Denounce": "She publicly denounced corruption.",
  "Denunciation": "The speech was a fierce denunciation of the regime.",
  "Epithet": "He hurled epithets at the referee.",
  "Excoriate": "Critics excoriated the film for its poor acting.",
  "Vituperative": "The debate became increasingly vituperative.",
  "Invective": "His speech was full of political invective.",
  "Pulverize": "The team pulverized their opponents.",
  "Subjugate": "The invaders subjugated the region.",
  "Vanquish": "They vanquished all their enemies.",
  "Subdue": "She tried to subdue her laughter.",
  "Capitulate": "The army capitulated after a long siege.",
  "Surrender": "The rebels finally surrendered.",
  "Doctrine": "The military follows a strict doctrine.",
  "Dogmas": "He challenged the religious dogmas of his time.",
  "Ideology": "Her ideology leaned towards environmentalism.",
  "Mandate": "The government issued a new health mandate.",
  "Tenets": "They follow the tenets of their faith.",
  "Principle": "He acted on principle rather than profit.",
  "Law": "Breaking the law has consequences.",
  "Canons": "She adhered to the canons of journalism.",
  "Unconventional": "She chose an unconventional career path.",
  "Dissident": "The dissident was arrested for his views.",
  "Heresy": "Questioning the king was seen as heresy.",
  "Heretical": "His heretical ideas caused controversy.",
  "Heterodox": "He held heterodox views on education.",
  "Iconoclast": "The artist was an iconoclast in his time.",
  "Insurgent": "Insurgent forces took control of the town.",
  "Insurrection": "The insurrection was quickly suppressed.",
  "Maverick": "She was a maverick in the tech industry.",
  "Nonconformist": "The nonconformist refused to follow the rules.",
  "Radical": "His radical views sparked debate.",
  "Renegade": "The renegade joined the rival group.",
  "Revolutionary": "It was a revolutionary idea for its time.",
  "Subversive": "The book was banned for its subversive content.",
  "Conservative Opposite": "His conservative nature made him wary of change.",
  "Conventional Opposite": "She preferred a conventional wedding.",
  "Orthodox Opposite": "He follows orthodox religious practices.",
  "Reactionary Opposite": "The reactionary group opposed all reforms.",
  "Revolt": "The people revolted against the dictator.",
  "Incite": "His speech incited the crowd to protest.",
  "Incendiary": "The article contained incendiary remarks.",
  "Instigate": "They instigated a fight in the hallway.",
  "Provoke": "He provoked her into reacting.",
  "Sedition": "He was arrested for sedition against the government.",
  "Captious": "She was being captious over minor details.",
  "Querulous": "He grew querulous after the long wait.",
  "Jeopardy": "The decision put his career in jeopardy.",
  "Peril": "Climbers face great peril on the mountain.",
  "Precarious": "The ladder looked precarious and unsafe.",
  "Snare": "He fell into the snare of deceit.",
  "Risk": "Investing in stocks involves risk.",
  "Ill-Will": "There was ill-will between the rivals.",
  "Malevolence": "Her eyes gleamed with malevolence.",
  "Malice": "He spoke with malice in his voice.",
  "Vicious": "It was a vicious attack on the victim.",
  "Virulent": "The politician launched a virulent speech.",
  "Beset": "They were beset by financial problems.",
  "Beleaguered": "The beleaguered company laid off employees.",
  "Plagued": "He was plagued by doubts.",
  "Disrespect": "Talking back shows disrespect.",
  "Banter": "Their banter kept the mood light.",
  "Belittle": "Don't belittle his achievements.",
  "Condescend": "She condescended to speak to the intern.",
  "Contempt": "He showed contempt for the rules.",
  "Denigrate": "She denigrated his efforts in front of others.",
  "Deride": "They derided his old-fashioned ideas.",
  "Disdain": "He looked at them with disdain.",
  "Disparage": "They disparaged the new policy.",
  "Jibe": "He threw a jibe at the speaker.",
  "Raillery": "The friendly raillery made everyone smile.",
  "Sarcastic": "His sarcastic tone was hard to miss.",
  "Taunt": "The bully taunted the younger kids.",
  "Scorn": "She replied with scorn and anger.",
  "Spurn": "He spurned the job offer.",
  "Acclaim": "The artist was met with acclaim.",
  "Accolade": "She received accolades for her work.",
  "Applaud": "The crowd applauded loudly.",
  "Approbation": "He earned the approbation of his peers.",
  "Commendable": "His honesty was commendable.",
  "Encomiastic": "The speech was encomiastic in tone.",
  "Exalt": "They exalted the hero for his bravery.",
  "Extol": "Critics extolled the performance.",
  "GLorify": "The book glorifies the leader.",
  "Hail": "He was hailed as a genius.",
  "Laud": "They lauded her contributions to science.",
  "Lionize": "The media lionized the athlete.",
  "Accentuate": "The lighting accentuated her features.",
  "Foreground": "The essay foregrounds the issue of poverty.",
  "Underscore": "The data underscores the need for action.",
  "Analogy": "He used an analogy to explain the concept.",
  "Antithetical Opposite": "Their views were antithetical to each other.",
  "Match": "Her skills match the job requirements.",
  "Coalesce": "Ideas coalesced into a clear strategy.",
  "Rally": "The team rallied after halftime.",
  "Commensurate": "Your responsibilities will be commensurate with your experience.",
  "Parity": "The two currencies achieved parity for the first time in decades.",
  "Peers": "She was respected by her peers for her integrity.",
  "Tantamount": "His silence was tantamount to an admission of guilt.",
  "Disparate": "They came from disparate backgrounds but shared common goals.",
  "Disparity": "There is a significant disparity between urban and rural healthcare.",  
  "Harmony": "They lived in harmony with nature.",
  "Accord": "The two countries signed a peace accord.",
  "Concord": "Their views were in complete concord.",
  "Conformity": "The school encouraged conformity in dress and behavior.",
  "Congruous": "His actions were congruous with his words.",
  "Consensus": "There was a consensus on the need for reform.",
  "Consonance": "Her values were in consonance with the team’s goals.",
  "Unanimity": "The proposal was accepted with complete unanimity.",
  "Understanding": "We reached an understanding after a long discussion.",  
  "Discord": "The decision led to discord among the board members.",
  "Discrepancy": "There was a discrepancy in the financial report.",
  "Dissonance": "There was emotional dissonance between his words and tone.",
  "Faction": "A faction within the party opposed the new policy.",
  "Incompatible": "Their work styles were incompatible.",
  "Irreconcilable": "They had irreconcilable differences and filed for divorce.",
  "Veto": "The president used his veto power to block the bill.",  
  "Chasm": "There was a growing chasm between the rich and the poor.",
  "Dichotomy": "The dichotomy between theory and practice is often debated.",
  "Gulf": "A wide gulf separates the two cultures.",
  "Rift": "A serious rift developed in their friendship.",
  "Schism": "The church suffered a major schism over doctrine.",
  "Gap": "There's a communication gap between generations.",  
  "Argumentative": "He became argumentative when questioned.",
  "Belligerent": "His belligerent attitude caused a scene.",
  "Bellicose": "The bellicose rhetoric raised tensions.",
  "Contetious": "The meeting became contentious over budget issues.",
  "Disputatious": "She had a disputatious nature in debates.",
  "Fractious": "The fractious crowd was hard to control.",
  "Hostility": "There was open hostility between the teams.",
  "Litigious": "The company avoided litigious customers.",
  "Polemical": "His polemical essay sparked controversy.",
  "Pugnacious": "He had a pugnacious personality.",
  "Truculent": "Her truculent remarks offended many.",  
  "Fight": "They had a fight over a minor issue.",
  "Altercation": "A loud altercation broke out in the hallway.",
  "Contend": "They contend that the policy is unfair.",
  "Row": "They had a row over household chores.",
  "Scuffle": "A brief scuffle erupted outside the bar.",
  "Tiff": "They had a tiff but made up quickly.",
  "Truce": "Both sides agreed to a temporary truce.",  
  "Taken Aback": "I was taken aback by her sudden anger.",
  "Astound": "The magician astounded the audience.",
  "Baffle": "The puzzle baffled even the experts.",
  "Bemuse": "He was bemused by the unexpected question.",
  "Bewilder": "Her response bewildered the interviewer.",
  "Confound": "His explanation confounded the critics.",
  "Nonplussed": "She was nonplussed by the strange request.",
  "Obfuscate": "The jargon only served to obfuscate the issue.",
  "Perplex": "The instructions perplexed everyone.",
  "Stupefy": "The news stupefied the nation.",  
  "Indifferent": "He was indifferent to the outcome.",
  "Apathetic": "She felt apathetic about politics.",
  "Aplomb": "He handled the crisis with aplomb.",
  "Composure": "She maintained her composure during the interview.",
  "Equanimity": "He accepted the bad news with equanimity.",
  "Impassive": "Her impassive expression gave nothing away.",
  "Imperturbable": "She remained imperturbable under pressure.",
  "Nonchalant": "He gave a nonchalant shrug.",
  "Phlegmatic": "His phlegmatic temperament kept him calm.",
  "Placid": "The lake was placid and still.",
  "Serene": "She had a serene look on her face.",
  "Tranquil": "The countryside was tranquil and beautiful.",
  "Staid": "He had a staid and proper demeanor.",
  "Stoic": "He remained stoic despite the pain.",  
  "Agitated": "She looked agitated after the meeting.",
  "Disconcert": "The sudden question disconcerted her.",
  "Dismay": "I was filled with dismay at the results.",
  "Disquiet": "There was a sense of disquiet in the room.",
  "Distraught": "She was too distraught to speak.",
  "Faze": "He wasn’t fazed by the criticism.",
  "Fluster": "She got flustered during the presentation.",
  "Frenetic": "They worked at a frenetic pace.",
  "Frenzied": "The fans gave a frenzied response.",
  "Hysterical": "She became hysterical with laughter.",
  "Implacable": "He was an implacable enemy.",
  "Perturb": "The news perturbed him greatly.", 
  "Alienate": "His rude behavior alienated his coworkers.",
  "Antagonize": "Try not to antagonize the interviewer.",
  "Estrange": "The argument estranged them for years.",  
  "Comprehensive": "We need a comprehensive plan.",
  "Encompass": "The book encompasses all aspects of science.",
  "Expansive": "He gave an expansive explanation.",
  "Inclusive": "The event was inclusive of all groups.",
  "Pervasive": "Corruption was pervasive in the system.",
  "Exhaustive": "We conducted an exhaustive search.",  
  "Omnipresent": "Social media is omnipresent today.",
  "Ubiquitous": "Smartphones have become ubiquitous.",
  "Insular": "His insular views made it hard for him to accept new ideas.",
  "Myopic": "Her myopic approach ignored the long-term consequences.",
  "Parochial": "He had a parochial mindset that dismissed global issues.",
  "Provincial": "Their provincial thinking limited their innovation.",
  "Regional": "The policy is too regional and doesn’t consider national impact.",
  "Partial": "The judge was accused of being partial in his decision.",
  "Bigot": "The bigot refused to listen to anyone with different views.",
  "Discriminatory": "The hiring policy was found to be discriminatory.",
  "Partisan": "His partisan speech alienated half the audience.",
  "Prejudiced": "She was prejudiced against those with different beliefs.",
  "Tendentious": "The article was tendentious and lacked objectivity.",
  "subjectivity": "Judges must avoid subjectivity and focus on facts.",
  "Impartial": "An impartial jury is crucial for a fair trial.",
  "Detached": "He remained detached from the emotional argument.",
  "Detachment": "Her detachment helped her make unbiased decisions.",
  "Disinterested": "We need a disinterested advisor to mediate the issue.",
  "Dispassionate": "He gave a dispassionate analysis of the data.",
  "Egalitarian": "The company promotes an egalitarian work environment.",
  "Equitable": "They reached an equitable solution for both parties.",
  "Even Handed": "The teacher was even handed with all students.",
  "Objectivity": "Reporters should maintain objectivity in their writing.",
  "Non-Serious": "He gave a non-serious response to a serious issue.",
  "Blithe": "She remained blithe despite the mounting pressure.",
  "Flippant": "His flippant remarks offended the audience.",
  "Frivolous": "They dismissed the complaint as frivolous.",
  "Frivolity": "There was no room for frivolity in the serious meeting.",
  "Levity": "He tried to bring levity to the tense discussion.",
  "Grave Opposite": "His comment lacked the grave tone the event required.",
  "Gravity Opposite": "She treated the announcement with a surprising lack of gravity.",
  "Antidote": "Laughter is a good antidote to stress.",
  "Panacea": "There’s no panacea for all economic problems.",
  "End": "The treaty helped end the decades-long conflict.",
  "Quell": "The police tried to quell the protest peacefully.",
  "Quash": "The court quashed the unfair regulation.",
  "Repress": "He struggled to repress his anger during the debate.",
  "Scotch": "They managed to scotch the rumors quickly.",
  "Subdue": "She had to subdue her nerves before the speech.",
  "Absolute": "The king ruled with absolute power.",
  "Authoritative": "He spoke in an authoritative tone that silenced the room.",
  "Autocrat": "The CEO was seen as an autocrat by the staff.",
  "Despot": "The despot was finally overthrown by the people.",
  "Dictate": "He tried to dictate terms without negotiation.",
  "Doctrinaire": "His doctrinaire stance ignored real-world issues.",
  "Dogmatic": "She gave a dogmatic argument that allowed no dissent.",
  "Imperious": "His imperious behavior annoyed his colleagues.",
  "Totalitarian": "The country suffered under a totalitarian regime.",
  "Tyrant": "The tyrant crushed all opposition brutally.",
  "Homogeneity": "The homogeneity of the group stifled innovation.",
  "Uniformity": "The uniforms created a sense of uniformity among students.",
  "Heterogeneity Opposite": "The lack of diversity showed heterogeneity's opposite.",
  "Precise": "Her precise measurements ensured a perfect recipe.",
  "Conscientious": "He is a conscientious worker who never misses a detail.",
  "Demanding": "The project was demanding but rewarding.",
  "Exacting": "Her exacting standards pushed the team to excel.",
  "Fastidious": "He is fastidious about keeping his workspace clean.",
  "Meticulous": "She planned the event with meticulous detail.",
  "Punctilious": "He was punctilious about following protocol.",
  "Scrupulous": "She’s scrupulous in maintaining ethical standards.",
  "Nice": "He’s too nice when judging other people’s work.",
  "Stickler": "She’s a stickler for grammar and formatting.",
  "Hard to Please": "He’s known to be hard to please with food.",
  "Cursory": "He gave the report only a cursory glance.",
  "Perfunctory": "Her perfunctory apology didn’t seem sincere.",
  "Summarily": "The issue was summarily dismissed.",
  "Superficially": "He understood the concept only superficially."
};
