const wordGroups = {
  "Sign": ["Forebode", "Foreshadow", "Ominous", "Premonition", "Warning"],
  "Causing fear": ["Daunting", "Intimidate", "Sinister"],
  "Flexible": ["Agile", "Lithe", "Supple"],
  "Attractive": ["Aesthetic", "Comely"],
  "Very Talented": ["Prodigy", "Precocious"],
  "Prediction": ["Anticipate", "Forecast", "Foresight", "Foresee", "Foretell", "Presage", "Prescience", "Prognosis"],
  "Very Angry": ["Enrage", "Fume","Incense", "Indignation", "Infuriate", "Irate", "Ire", "Livid", "Wrath"],
  "Detailed Knowledge": ["Intellectual", "Cerebral", "Erudite", "Enlightened","Enlightenment", "Pundit", "Refined", "Refinement"],
  "SkillFull": ["Adept", "Adroit", "Consummate", "Deft", "Dexterous", "Finesse","Proficient", "Prowess", "Inept Opposite", "Maladroit Opposite"],
  "Having Twist": ["Turn", "Complex", "Circuitous", "Convulated", "Complicated", "Interwined", "Involved", "Meander", "Tortuous"],
  "Inclination": ["Affinity", "Aptitude", "Bent", "Disposed", "Penchant", "Predilection", "Predisposition", "Proclivity", "Prospensity"],
  "Ineffective": ["Futile", "Ineffectual", "Efficacy Oppose", "Feckless Similar"],
  "Horryfing": ["Shocking", "Aghast", "Apalling", "Egregious", "Ghastly", "Gross", "Gruesome", "Heinous", "Hideous", "Horrendous", "Monstrous", "Morbid", "Unsightly", "Vile"],
  "Separate": ["Disjointed", "Polarize", "Segregate", "Connected Opposite", "Nexus Opposite"],
  "Avoid": ["Dodge", "Avert", "Circumvent", "Deflect", "Elude", "Elusive", "Evade", "Evasive", "Shirk", "Skirt", "Swerve", "Head-on Opposite", "Inevitable Opposite", "Unavoidable opposite"],
  "Awkward": ["Clumsy", "Fumble", "Gauche", "Gawky", "Ungainly"],
  "Optimistic": ["Buoyant", "Sanguine", "Upbeat"],
  "Be slow": ["Waste time", "Dilatory", "Linger", "Malinger"],
  "Instructive" : ["Didactic", "Pedantic", "Sophist"],
  "Spread": ["Diffuse", "Disseminate", "Promulgate", "Propagate"],
  "Excessive Flattery": ["Adulation", "Obsequious", "Sycophant"],
  "Bodily": ["Anatomical", "Corporeal", "Physiological"],
  "Hate": ["Animosity", "Antipathy", "Aversion", "Despicable", "Detest", "Loathe", "Repel", "Repugnant", "Repulsion"],
  "Old Fashioned": ["Antiquated", "Archaic", "Dated", "Obsolete", "Outmoded", "Quaint", "Outdated"],
  "Arranged in Time": ["Chronicle", "Chronological"],
  "Co-existing": ["Contemporary", "Simultaneous", "Erstwhile Opposite", "Anachronism Opposite"],
  "Cautious": ["Careful", "Risky Opposite","Caveat", "Circumspect", "Heedful", "Prudent", "Wary", "Folly Opposite", "Rash Opposite", "Reckless Opposite"],
  "Self-Satisfaction": ["Bask", "Complacent"],
  "Scolding": ["Admonish", "Berate", "Censure", "Chastise", "Rebuke", "Reprimand", "Reproach", "Upbraid"],
  "Criticize": ["Assail", "Castigate", "Decry", "Denounce", "Denunciation", "Epithet", "Excoriate", "Vituperative", "Invective"],
  "To Defeat": ["Pulverize", "Subjugate", "Vanquish", "Subdue", "Capitulate", "Surrender"],  
  "Rule": ["Doctrine", "Dogmas", "Ideology", "Mandate", "Tenets", "Principle", "Law", "Canons"],
  "Rebellious": ["Unconventional", "Dissident", "Heresy", "Heretical", "Heterodox", "Iconoclast", "Insurgent", "Insurrection", "Maverick", "Nonconformist", "Radical", "Renegade", "Revolutionary", "Subversive", "Conservative Opposite", "Conventional Opposite", "Orthodox Opposite", "Reactionary Opposite"],
  "To Stir Up": ["Revolt", "Incite", "Incendiary", "Instigate", "Provoke", "Sedition"],
  "Complain (Low Degree)": ["Captious", "Querulous"],
  "Danger": ["Jeopardy", "Peril", "Precarious", "Snare", "Risk"],
  "Bitter Feelings": ["Ill-Will", "Malevolence", "Malice", "Vicious", "Virulent"],
  "Troubled": ["Beset", "Beleaguered", "Plagued"],
  "Mock": ["Disrespect", "Banter", "Belittle", "Condescend", "Contempt", "Denigrate","Deride", "Disdain", "Disparage", "Jibe","Raillery", "Sarcastic", "Taunt", "Scorn", "Spurn"],
  "Praise": ["Acclaim", "Accolade", "Applaud", "Approbation", "Commendable", "Encomiastic", "Exalt", "Extol", "GLorify", "Hail", "Laud", "Lionize"],
  "Emphasize": ["Accentuate", "Foreground", "Underscore"],
  "Similarity": ["Analogy", "Antithetical Opposite", "Match"],
  "Coming Together": ["Coalesce", "Rally"],
  "Equality": ["Commensurate", "Parity", "Peers", "Tantamount", "Disparate Opposite", "Disparity Opposite"],
  "Agreement": ["Harmony", "Accord", "Concord", "Conformity", "Congruous", "Consensus", "Consonance", "Unanimity", "Understanding"],
  "Disagreement": ["Discord", "Discrepancy", "Dissonance", "Faction", "Incompatible", "Irreconcilable", "Veto"],
  "Split": ["Chasm", "Dichotomy", "Gulf", "Rift", "Schism", "Gap"],
  "Aggressive": ["Argumentative", "Belligerent", "Bellicose", "Contetious", "Disputatious", "Fractious", "Hostility", "Litigious", "Polemical", "Pugnacious", "Truculent"],
  "Argue": ["Fight", "Altercation", "Contend", "Row", "Scuffle", "Tiff", "Truce Opposite"],
  "Confused": ["Taken Aback", "Astound", "Baffle", "Bemuse", "Bewilder", "Confound", "Nonplussed", "Obfuscate", "Perplex", "Stupefy"],
  "Calm": ["Indifferent", "Apathetic", "Aplomb", "Composure", "Equanimity", "Impassive", "Imperturbable", "Nonchalant", "Phlegmatic", "Placid", "Serene", "Tranquil", "Staid", "Stoic"],
  "Disturbed": ["Agitated", "Disconcert", "Dismay", "Disquiet", "Distraught", "Faze", "Fluster", "Frenetic", "Frenzied", "Hysterical", "Implacable", "Perturb"],
  "Make Hostile": ["Alienate", "Antagonize", "Estrange"],
  "Include Everything": ["Comprehensive", "Encompass", "Expansive", "Inclusive", "Pervasive", "Exhaustive"],
  "Present Everywhere": ["Omnipresent", "Ubiquitous"],
  "Narrow Minded": ["Insular", "Myopic", "Parochial", "Provincial", "Regional"],
  "Biased": ["Partial", "Bigot", "Discriminatory", "Partisan", "Prejudiced", "Tendentious", "subjectivity"],
  "Unbiased": ["Impartial", "Detached", "Detachment", "Disinterested", "Dispassionate", "Egalitarian", "Equitable", "Even Handed", "Objectivity"],
  "Disrespectfully Casual": ["Non-Serious", "Blithe", "Flippant", "Frivolous","Frivolity", "Levity", "Grave Opposite", "Gravity Opposite"],
  "Cure": ["Antidote", "Panacea"],
  "Suppress": ["End", "Quell", "Quash", "Repress", "Scotch", "Subdue"],
  "Dominating": ["Absolute", "Authoritative", "Autocrat", "Despot", "Dictate","Doctrinaire", "Dogmatic", "Imperious", "Totalitarian", "Tyrant"],
  "Being Alike": ["Homogeneity", "Uniformity", "Heterogeneity Opposite"],
  "Thorough": ["Precise", "Conscientious", "Demanding", "Exacting", "Fastidious", "Meticulous", "Punctilious", "Scrupulous"],
  "Fussy": ["Nice", "Stickler", "Hard to Please"],
  "Not Thorough": ["Cursory", "Perfunctory", "Summarily", "Superficially"]

};