const wordGroups = {
  "Sign": ["Forebode", "Foreshadow", "Ominous", "Premonition", "Warning"],
  "Causing fear": ["Daunting", "Intimidate", "Sinister"],
  "Flexible": ["Agile", "Lithe", "Supple"],
  "Attractive": ["Aesthetic", "Comely"],
  "Very Talented": ["Prodigy", "Precocious"],
  "Prediction": ["Anticipate", "Forecast", "Foresight", "Foresee", "Foretell", "Presage", "Prescience", "Prognosis"],
  "Very Angry": ["Enrage", "Fume","Incense", "Indignation", "Infuriate", "Irate", "Ire", "Livid", "Wrath"],
  "Detailed Knowledge": ["Intellectual", "Cerebral", "Erudite", "Enlightened","Enlightenment", "Pundit", "Refined", "Refinement"],
  "SkillFull": ["Adept", "Adroit", "Consummate", "Deft", "Dexterous", "Finesse","Proficient", "Prowess", "Inept Opposite", "Maladroit Opposite"],
  "Having Twist": ["Turn", "Complex", "Circuitous", "Convulated", "Complicated", "Interwined", "Involved", "Meander", "Tortuous"],
  "Inclination": ["Affinity", "Aptitude", "Bent", "Disposed", "Penchant", "Predilection", "Predisposition", "Proclivity", "Prospensity"],
  "Ineffective": ["Futile", "Ineffectual", "Efficacy Oppose", "Feckless Similar"],
  "Horryfing": ["Shocking", "Aghast", "Apalling", "Egregious", "Ghastly", "Gross", "Gruesome", "Heinous", "Hideous", "Horrendous", "Monstrous", "Morbid", "Unsightly", "Vile"],
  "Separate": ["Disjointed", "Polarize", "Segregate", "Connected Opposite", "Nexus Opposite"],
  "Avoid": ["Dodge", "Avert", "Circumvent", "Deflect", "Elude", "Elusive", "Evade", "Evasive", "Shirk", "Skirt", "Swerve", "Head-on Opposite", "Inevitable Opposite", "Unavoidable opposite"],
  "Awkward": ["Clumsy", "Fumble", "Gauche", "Gawky", "Ungainly"],
  "Optimistic": ["Buoyant", "Sanguine", "Upbeat"],
  "Be slow": ["Waste time", "Dilatory", "Linger", "Malinger"],
  "Instructive" : ["Didactic", "Pedantic", "Sophist"],
  "Spread": ["Diffuse", "Disseminate", "Promulgate", "Propagate"],
  "Excessive Flattery": ["Adulation", "Obsequious", "Sycophant"],
  "Bodily": ["Anatomical", "Corporeal", "Physiological"],
  "Hate": ["Animosity", "Antipathy", "Aversion", "Despicable", "Detest", "Loathe", "Repel", "Repugnant", "Repulsion"],
  "Old Fashioned": ["Antiquated", "Archaic", "Dated", "Obsolete", "Outmoded", "Quaint", "Outdated"],
  "Arranged in Time": ["Chronicle", "Chronological"],
  "Co-existing": ["Contemporary", "Simultaneous", "Erstwhile Opposite", "Anachronism Opposite"],
  "Cautious": ["Careful", "Risky Opposite","Caveat", "Circumspect", "Heedful", "Prudent", "Wary", "Folly Opposite", "Rash Opposite", "Reckless Opposite"],
  "Self-Satisfaction": ["Bask", "Complacent"],
  "Scolding": ["Admonish", "Berate", "Censure", "Chastise", "Rebuke", "Reprimand", "Reproach", "Upbraid"],
  "Criticize": ["Assail", "Castigate", "Decry", "Denounce", "Denunciation", "Epithet", "Excoriate", "Vituperative", "Invective"],
  "To Defeat": ["Pulverize", "Subjugate", "Vanquish", "Subdue", "Capitulate", "Surrender"],  
  "Rule": ["Doctrine", "Dogmas", "Ideology", "Mandate", "Tenets", "Principle", "Law", "Canons"],
  "Rebellious": ["Unconventional", "Dissident", "Heresy", "Heretical", "Heterodox", "Iconoclast", "Insurgent", "Insurrection", "Maverick", "Nonconformist", "Radical", "Renegade", "Revolutionary", "Subversive", "Conservative Opposite", "Conventional Opposite", "Orthodox Opposite", "Reactionary Opposite"],
  "To Stir Up": ["Revolt", "Incite", "Incendiary", "Instigate", "Provoke", "Sedition"],
  "Complain (Low Degree)": ["Captious", "Querulous"],
  "Danger": ["Jeopardy", "Peril", "Precarious", "Snare", "Risk"],
  "Bitter Feelings": ["Ill-Will", "Malevolence", "Malice", "Vicious", "Virulent"],
  "Troubled": ["Beset", "Beleaguered", "Plagued"],
  "Mock": ["Disrespect", "Banter", "Belittle", "Condescend", "Contempt", "Denigrate","Deride", "Disdain", "Disparage", "Jibe","Raillery", "Sarcastic", "Taunt", "Scorn", "Spurn"],
  "Praise": ["Acclaim", "Accolade", "Applaud", "Approbation", "Commendable", "Encomiastic", "Exalt", "Extol", "GLorify", "Hail", "Laud", "Lionize"],
  "Emphasize": ["Accentuate", "Foreground", "Underscore"],
  "Similarity": ["Analogy", "Antithetical Opposite", "Match"],
  "Coming Together": ["Coalesce", "Rally"],
  "Equality": ["Commensurate", "Parity", "Peers", "Tantamount", "Disparate Opposite", "Disparity Opposite"],
  "Agreement": ["Harmony", "Accord", "Concord", "Conformity", "Congruous", "Consensus", "Consonance", "Unanimity", "Understanding"],
  "Disagreement": ["Discord", "Discrepancy", "Dissonance", "Faction", "Incompatible", "Irreconcilable", "Veto"],
  "Split": ["Chasm", "Dichotomy", "Gulf", "Rift", "Schism", "Gap"],
  "Aggressive": ["Argumentative", "Belligerent", "Bellicose", "Contetious", "Disputatious", "Fractious", "Hostility", "Litigious", "Polemical", "Pugnacious", "Truculent"],
  "Argue": ["Fight", "Altercation", "Contend", "Row", "Scuffle", "Tiff", "Truce Opposite"],
  "Confused": ["Taken Aback", "Astound", "Baffle", "Bemuse", "Bewilder", "Confound", "Nonplussed", "Obfuscate", "Perplex", "Stupefy"],
  "Calm": ["Indifferent", "Apathetic", "Aplomb", "Composure", "Equanimity", "Impassive", "Imperturbable", "Nonchalant", "Phlegmatic", "Placid", "Serene", "Tranquil", "Staid", "Stoic"],
  "Disturbed": ["Agitated", "Disconcert", "Dismay", "Disquiet", "Distraught", "Faze", "Fluster", "Frenetic", "Frenzied", "Hysterical", "Implacable", "Perturb"],
  "Make Hostile": ["Alienate", "Antagonize", "Estrange"],
  "Include Everything": ["Comprehensive", "Encompass", "Expansive", "Inclusive", "Pervasive", "Exhaustive"],
  "Present Everywhere": ["Omnipresent", "Ubiquitous"],
  "Narrow Minded": ["Insular", "Myopic", "Parochial", "Provincial", "Regional"],
  "Biased": ["Partial", "Bigot", "Discriminatory", "Partisan", "Prejudiced", "Tendentious", "subjectivity"],
  "Unbiased": ["Impartial", "Detached", "Detachment", "Disinterested", "Dispassionate", "Egalitarian", "Equitable", "Even Handed", "Objectivity"],
  "Disrespectfully Casual": ["Non-Serious", "Blithe", "Flippant", "Frivolous","Frivolity", "Levity", "Grave Opposite", "Gravity Opposite"],
  "Cure": ["Antidote", "Panacea"],
  "Suppress": ["End", "Quell", "Quash", "Repress", "Scotch", "Subdue"],
  "Dominating": ["Absolute", "Authoritative", "Autocrat", "Despot", "Dictate","Doctrinaire", "Dogmatic", "Imperious", "Totalitarian", "Tyrant"],
  "Being Alike": ["Homogeneity", "Uniformity", "Heterogeneity Opposite"],
  "Thorough": ["Precise", "Conscientious", "Demanding", "Exacting", "Fastidious", "Meticulous", "Punctilious", "Scrupulous"],
  "Fussy": ["Nice", "Stickler", "Hard to Please"],
  "Not Thorough": ["Cursory", "Perfunctory", "Summarily", "Superficially"],
  "SHORT-LIVED": ["EPHEMERAL", "EVANESCENT", "FLEETING", "TRANSIENT", "TRANSITORY", "MOMENTARY"],
  "NEVER ENDING": ["NON STOP", "CHRONIC", "INCESSANT", "INEXORABLE", "INTERMINABLE", "PERENNIAL", "RELENTLESS"],
  "END": ["STOP", "TERMINATE", "CULMINATE", "CEASE", "CESSATION"],
  "IRREGULAR": ["PERIODICALLY", "FITFULLY", "INTERMITTENT", "OCCASIONAL", "SPORADIC"],
  "CALM DOWN": [ "TO MAKE LESS WORSE", "ALLAY", "ALLEVIATE", "AMELIORATE", "APPEASE", "ASSUAGE", "CONCILIATE", "EXTENUATING", "MITIGATE", "MOLLIFY", "PACIFY", "PLACATE", "PROPITIATE", "SOLACE", "TEMPER", "EXACERBATE Opposite"],
  "LACKING ENERGY": ["JADED", "LACKADAISICAL", "LACKLUSTER", "LANGUID", "LASSITUDE", "LETHARGIC", "LISTLESS", "LAZY"],
  "HARDWORKING": ["ASSIDUOUS", "DILIGENT", "INDUSTRIOUS", "PAINSTAKING", "TOIL"],
  "HAPPY": ["JOYOUS", "BEAM", "ECSTASY", "ELATED", "EUPHORIA", "EXHILARATION", "EXULTANT", "GAIETY", "JOVIAL", "REGALE", "UPROARIOUS"],
  "UNIMPORTANT": ["TRIVIAL", "EXPENDABLE", "FRINGE", "INCIDENTAL", "INCONSEQUENTIAL", "MARGINALIZATION", "PERIPHERAL"],
  "SAD": ["ANGUISH", "BEREAVED", "BLEAK", "CRESTFALLEN", "DEJECTED", "DESOLATE", "DESPONDENT", "LAMENT", "MELANCHOLY", "WOE", "PATHOS", "POIGNANT", "DESPAIR", "DEPRESSED"],
  "ENTHUSIASTIC": [ "EXCITED", "ARDOR", "ARDENT", "AVID", "DYNAMIC", "EBULLIENT", "EFFERVESCENT", "EXUBERANT", "FERVENT/FERVOR", "IMPASSIONED", "VIVACIOUS", "ZEALOUS", "ZEST", "DAMPEN Opposite", "TEPID Opposite", "RHAPSODY Similar"],
  "UNUSUAL": ["EXCEPTION", "ABERRATION", "ANOMALY", "DEVIATE"],
  "ORDINARY": ["UNORIGINAL","BANAL", "CLICHE", "COMMONPLACE", "DERIVATIVE", "HACKNEY", "HUMDRUM", "MUNDANE", "PEDESTRIAN", "PLATITUDE", "QUOTIDIAN", "TRITE", "UNREMARKABLE", "BROMIDE", "PROSAIC"],
  "DIFFICULT TO UNDERSTAND": ["OPAQUE", "ABSTRACT", "ABSTRUSE", "ARCANE", "ESOTERIC", "MYSTICAL", "OBSCURE", "RECONDITE", "PROFOUND" ,"PROFUNDITY", "PERSPICUOUS Opposite"],
  "CRUCIAL": ["SIGNIFICANT", "CORE", "FOREMOST", "IMPERATIVE", "INDISPENSABLE", "MANDATORY", "MOMENTOUS", "PIVOTAL", "SALIENT"],
  "ENERGIZING": ["INVIGORATING", "REVITALIZING"],
  "INACTIVE": ["DORMANT", "STAGNANT"],
  "BORING": ["VAPID", "BLAND", "INSIPID", "DRAB", "DULL"],
  "REPETITIOUS THUS BORING": ["MONOTONOUS", "TEDIOUS", "PLOD"],
  "UNWILLING TO SPEND": ["SPENDING WISELY", "CLOSEFISTED", "MISERLY", "PARSIMONIOUS", "STINGY", "TIGHTFISTED", "THRIFT Similar", "FRUGAL Similar", "HUSBANDRY Similar", "ECONOMICAL Similar", "ECONOMY Similar"],
  "COMBINE": ["AMALGAMATE", "COALITION", "MELD", "SYNTHESIS", "INTEGRATE", "PAIRING"],
  "VERY LESS": ["EXIGUOUS", "MEAGER", "PUNY", "SCANTY", "SPARSE", "SCARCE"],
  "UNCLEAR IN MEANING": ["AMBIVALENT", "AMBIGUOUS", "EQUIVOCAL"],
  "EXCESSIVE PATRIOTISM": ["FANATIC", "ZEALOT", "IDEALOGUE"],
  "REMEMBERING THE PAST": ["EVOCATIVE", "HINDSIGHT", "NOSTALGIA", "REMINISCENCE", "RETROSPECT", "WISTFUL"],
  "LUCKY": ["FORTUITOUS", "OPPORTUNE", "PROPITIOUS", "SERENDIPITY", "HAPLESS Opposite", "UNLUCKY Opposite"],
  "WEALTHY": ["OPULENT", "AFFLUENT"],
  "PAIN": ["SUFFERING", "ADVERSITY", "AFFLICTIONS", "MISHAP", "ORDEALS", "TRIALS", "TRIBULATION"],
  "ROUTINE BEHAVIOR": ["OBTAIN", "WONT"],
  "RELEVANT": ["GERMANE", "PERTINENT"],
  "EXCESS": ["ABOUND", "COPIOUS", "MYRIAD", "PLETHORA", "PROFUSE", "PROLIFIC", "STEEPED", "SURFEIT", "SURGE"],
  "REDUCE": ["CONSTRICT", "CONTRACT", "CURTAIL", "DWINDLE", "FLAG", "WANE", "RETRENCH", "RESTRICT"],
  "INCREASE": ["ACCRETION", "AGGRANDIZE", "AUGMENT", "BALLOON", "DILATE", "ENHANCE", "MOUNTING", "PROLIFERATE", "WAX", "BURGEON Similar", "MAGNIFY"],
  "EXPLAIN TOO MUCH": ["BELABOR", "UNDERSTATEMENT Opposite"],
  "LESSEN IN INTENSITY": ["ABATE", "EBB", "RECEDE", "SUBSIDE"],
  "VERY HIGH PRICE": ["EXORBITANT", "PROHIBITIVE"],
  "CANNOT BE DEFEATED": ["IMPERVIOUS", "INDOMITABLE", "INVINCIBLE", "IMPENETRABLE"],
  "SHORTAGE": ["DEFICIT", "PAUCITY", "WANTING", "DEVOID", "DEPRIVED", "LACKING"],
  "POOR": ["IMPECUNIOUS", "IMPOVERISH", "INDIGENT"],
  "SPEND LAVISHLY": ["PRODIGAL", "PROFLIGATE", "SPENDTHRIFT", "SQUANDER", "EXTRAVAGANCE", "LAVISH", "WASTE"],
  "FAREWELL": ["VALEDICTORY", "PARTING", "MIGRATION", "TO GO AWAY"],
  "TO RISE BEYOND": ["TRANSCEND", "SURPASS", "OUTSTRIP"],
  "NERVOUS": ["RESTIVE", "SKITTISH", "RESTLESS"],
  "COMPETITIVENESS": ["AMBITIOUS", "OPPORTUNISM", "ASPIRATION"],
  "SURE": ["CERTAIN", "ABSOLUTE", "CATEGORICAL", "CERTITUDE", "CONVICTION", "EMPHATIC", "INCONTROVERTIBLE", "UNQUALIFIED", "CONTINGENT Opposite", "PROVISIONAL Opposite", "INCONCLUSIVE Opposite", "QUALIFIED Opposite", "CONDITIONAL Opposite"],
  "RELATED": ["KINDRED", "AFFILIATED"],


  "PLEASANT SOUNDING": ["EUPHONY", "MELODIOUS", "MELLIFLUOUS"],
  "GREED": ["AVARICE", "COVETOUS", "GLUTTON (food)", "VORACIOUS"],
  "OVERLY NOISY": ["CACOPHONY", "CLAMOR", "CLANGOR", "DISCORDANT", "RAUCOUS", "STRIDENT", "VOCIFEROUS", "INAUDIBLE Opposite"],
  "SUPPORTER": ["ADVOCATE", "ALLY", "CHAMPION", "ENDORSE", "ESPOUSE", "LOBBYIST", "PROPONENT", "PROTAGONIST", "ADVERSARY Opposite", 
  "ANTAGONIST Opposite", "DETRACTOR Opposite", "FOE Opposite", "IMPUGN Opposite", "INIMICAL Opposite", "NEMESIS Opposite"],
  "RESOLUTE": ["ENDURE", "IMMUTABLE", "INDEFATIGABLE", "PERSEVERE", "PERSISTENCE", "RESOLUTE", "STEADFAST", "TENACIOUS"],
  "STUBBORN": ["OBDURATE", "ADAMANT", "DEFIANT", "INCORRIGIBLE", "INTRACTABLE", "INTRANSIGENT", "OBSTINATE", "PERVERSE", "RECALCITRANT", "REFRACTORY"],
  "ACCEPT": ["ACCEDE", "ACQUIESCE", "AMENABLE", "ASSENT", "COMPLIANT", "COMPLY", "CONCEDE", "PLIANT", "RELENT", "SUCCUMB", "YIELD", "DOCILE (easily controlled)", "MALLEABLE (easily controlled)", "AGREE", "GIVE IN"],
  "TO MAKE UP": ["CONCOCT", "DEVISE", "FORMULATE", "CONJURE", "CREATE"],
  "PLANNED": ["AD-HOC Opposite", "CALCULATED", "DELIBERATE", "FORETHOUGHT", "INTENTIONAL", "PREMEDITATED", "STUDIED", "EXTEMPORANEOUS Opposite", "IMPETUOUS Opposite", "IMPROMPTU Opposite", "IMPROVISE Opposite"],
  "EXTRA HENCE UNNECESSARY": ["EXTRANEOUS", "REDUNDANT", "SUPERFLUOUS"],
  "TO PROVE FALSE": ["BELIE", "DEBUNK", "DISCREDIT", "EXPOSTULATE", "REBUT", "REFUTE"],
  "PROFITABLE": ["REMUNERATIVE", "LUCRATIVE"],
  "TO OBJECT": ["DEFY", "DEMUR", "DISSENT", "TAKE ISSUE WITH"],
  "VILLAGE-LIKE": ["BUCOLIC", "PASTORAL", "RUSTIC"],
  "FAMOUS": ["EMINENT", "LUMINARY", "PRE-EMINENT", "PREEMINENCE", "STATURE"],
  "BREAK A RULE": ["BREACH", "FLOUT", "TRANSGRESS", "ABIDE Opposite", "ADHERE Opposite", "INFRACTION"],
  "FICKLE": ["ARBITRARY", "CAPRICIOUS", "ERRATIC", "INCONSISTENT", "IRRESOLUTE", "MERCURIAL", "OSCILLATE", "SWAY", "TEMPERAMENTAL", "VOLATILE", "WAFFLE", "WAVER", "WHIMSICAL"],
  "INDIRECT EXPERIENCE": ["VICARIOUS"],
  "CONFIRM": ["ASCERTAIN", "AFFIRM", "CORROBORATE", "RATIFY", "SUBSTANTIATE", "TESTIFY", "TESTIMONY", "VALIDATE", "UNFOUNDED Opposite"],
  "SEVERE": ["ACUTE", "AUSTERE"],
  "CLOTHING": ["SARTORIAL", "RAIMENT"],
  "SEVERE": ["ACUTE", "AUSTERE"],
  "BREAK A RULE": ["BREACH", "FLOUT", "TRANSGRESS", "ABIDE Opposite", "ADHERE Opposite", "INFRACTION"],
  "ACHIEVEMENT": ["ACCOMPLISHMENT", "TRIUMPH"],

  "JUST BEGINNING OR DEVELOPING": ["INFANCY", "INCIPIENT", "NASCENT", "INCEPTION"],
  "TO LOSE STRENGTH": [ "TO WEAKEN", "ATROPHY", "ATTENUATE", "ATTRITION", "DEBILITATE", "DEGENERATE", "DEGRADATION", "ENERVATE", "ENFEEBLE", "FLAGGING", "WITHER", "ERODE", "UNDERCUT", "UNDERMINE", "SUBVERT", "RETROGRADE"],
  "DISLOYALTY": ["BETRAY", "TREACHERY", "TREACHEROUS", "TREASON"],
  "INTERVAL": ["ABEYANCE", "HIATUS", "LULL", "RESPITE", "PAUSE"],
  "CLEAR (BOTH PHYSICALLY AND IN MEANING)": ["CLARITY", "ELUCIDATE", "EXPOUND", "LUCID", "PELLUCID"],
  "EXPERT": ["CONNOISSEUR", "LAYPERSON Opposite", "VIRTUOSO"],
  "SUMMARY": ["CRUX", "GIST", "PURPORT", "SYNOPSIS"],
  "CORRECT or REPAIR": ["AMEND", "EXPIATE", "INDEMNIFY", "REDEMPTION", "REDRESS", "REPARATION", "COMPENSATE", "COUNTERBALANCE"],
  "FEELING GUILTY": ["CONTRITE", "PENITENT", "REMORSE", "RUEFUL"],
  "EXPERIENCED": ["SEASONED", "VETERAN"],
  "HAPPENING BEFORE MAIN EVENT": ["ANTECEDENT", "FORERUNNER", "HARBINGER", "PRECEDENT", "PRECURSOR", "ANTEDATE"],
  "STRANGE": ["ECCENTRIC", "IDIOSYNCRASY", "QUIRKINESS"],
  "RESTRAIN": ["BRIDLE", "CIRCUMSCRIBE", "CONSTRAINT", "FETTER", "REIN", "SECURE", "SHACKLE", "EXTRICATE Opposite", "MANACLE", "EMANCIPATE Opposite", " SET FREE Opposite"],
  "RESTORED": ["REGENERATE", "REJUVENATE", "REVIVE", "RESURRECT", "RENAISSANCE"],
  "IDEALISTIC": ["QUIXOTIC", "UTOPIAN"],
  "IMMORAL": [ "DECADENT", "DEGENERATE", "DEPRAVITY", "DISSOLUTE", "IMPROBITY", "WAYWARD", "IRREPROACHABLE Opposite", "INTEGRITY Opposite", "PROBITY Opposite", "RECTITUDE Opposite", "UNIMPEACHABLE Opposite", "CONSCIENCE Opposite"],
  "UNCLEAR / HAZY": ["BECLOUD", "INDISTINCT", "MURKY", "NEBULOUS", "OBSCURE"],
  "DIFFICULT": ["ARDUOUS", "CUMBERSOME", "EXACTING", "ONEROUS", "LABORIOUS", "FACILE Opposite"],
  "HARMFUL": [ "CURSE", "BANE", "BLIGHT", "DELETERIOUS", "DETRIMENTAL", "MALIGNANT", "PERNICIOUS", "BENIGN Opposite", "INNOCUOUS Opposite", "INSIDIOUS", "BOON Opposite"],
  "INDEPENDENCE": ["AUTONOMY", "LATITUDE", "SOVEREIGN", "FREEDOM"],
  "DIFFICULTY or CONFUSING SITUATION": ["DILEMMA", "PREDICAMENT", "QUANDARY"],
  "TO DISPLACE": ["SUPPLANT", "SUPERSEDE"],
  "PERFECT": ["FLAWED Opposite", "FLAWLESS", "IMMACULATE", "IMPECCABLE", "INFALLIBLE", "FOIBLE Opposite"],
  "TO DEFINE": ["DELINEATE", "DEPICT", "DELIMIT", "OUTLINE", "DESCRIBE"],
  "CRIMINALS": ["MENACE", "MISCREANT", "LAW-BREAKERS"],
  "CHAOS": ["PANDEMONIUM", "TUMULTUOUS", "TURBULENCE", "TURMOIL", "UPHEAVAL", "CONFUSION"],
  "DOUBTFUL": ["APPREHENSIVE", "CYNICAL", "DUBIOUS", "QUESTIONABLE", "SKEPTICAL"],
  "SHINING": ["BURNISHED", "EFFULGENT", "LUMINOUS", "LUSTROUS", "SCINTILLATING"],
  "SELF CONTROL": ["MODERATE", "REFRAIN", "TEMPERATE", "X INDULGE Opposite"],
  "DISASTER": ["CALAMITOUS", "CATASTROPHE", "DEBACLE", "X COUP Opposite"],
  "SHOW - OFF (-)": [ "FLAMBOYANCE", "FLAUNT", "GRANDIOSE", "OSTENTATIOUS", "PRETENTIOUS", "PANACHE (+)", "*BRANDISH (wave emotionally)", "X UNPRETENTIOUS Opposite"],
  "CHEAT": ["DECEIVE", "ARTFUL", "ARTIFICE", "CRAFTY", "DUPLICITY", "DUPE", "GUILE", "MISLEAD", "SWINDLE"],
  "SPEAK LESS or FEW WORDS": ["ABRIDGE", "BREVITY", "CONDENSE", "PITHY", "RETICENT", "SUCCINCT", "TACITURN", "TERSE"],
  "PRACTICAL": ["POSSIBLE", "CONCEIVABLE", "FEASIBLE", "PLAUSIBLE", "PRAGMATIC", "UTILITARIAN", "VIABLE", "PROBABLE", "X IMPROBABLE Opposite"],
  "DISRESPECTFULLY BOLD (-)": ["AUDACIOUS", "BRAZEN", "IMPERTINENT", "IMPUDENT", "INSOLENT", "PRESUMPTUOUS"],
  "GENEROUS SUPPORTER or PROVIDER": [ "ALTRUIST", "BENEFACTOR", "BENEFICENT", "BENEVOLENT", "HUMANE", "MAGNANIMOUS", "MUNIFICENT", "PATRON", "PHILANTHROPIST", "BENIGNITY/BENIGNANT"],
  "SPIRITUAL": ["SUBLIME", "BASE Opposite", "EARTHLY Opposite"],
  "TALKATIVE or LOTS OF WORDS": ["GARRULOUS", "LOQUACIOUS", "PROLIX", "VERBOSE", "VOLUBLE", "LONG-WINDED"],
  "COULD BE TRUE": ["CREDENCE", "CREDIBLE", "VERISIMILAR"],
  "REPEAT": ["RECAPITULATE", "REITERATE"],
  "EASILY FOOLED": ["INNOCENT", "ARTLESS", "CREDULOUS", "GUILELESS", "GULLIBLE", "NAIVE", "NAIVETE", "INGENUOUS", "DUPE", "WORLDLY-WISE Opposite", "X COSMOPOLITAN Opposite"],
  "DISREGARD": ["DISCOUNT", "BRUSH ASIDE"],
  "PRETENSE OF MORALITY (-)": ["HYPOCRITICAL", "PRUDE"],
  "AFTER EFFECTS": ["RAMIFICATIONS", "REPERCUSSIONS", "ENSUE"],
  "INAPPROPRIATE or IMPROPER BEHAVIOUR": [ "INDECOROUS", "DEMURE Opposite", "UNSEEMLY", "MALFEASANCE", "UNBECOMING", "FLAGRANT"],
  "OVERLY PROUD (-)": [ "ARROGANT", "BRAGGART", "CONCEITED", "EGOTISTICAL", "HAUGHTY", "POMPOUS", "VAINGLORIOUS", "X UNASSUMING Opposite", "ELITIST", "CAVALIER", "NARCISSISM"],
  "TO GIVE CONTROL/RESPONSIBILITY": ["DELEGATE", "DEVOLVE"],
  "HESITATE ON MORAL GROUNDS": ["MISGIVINGS", "SCRUPLES", "UNSCRUPULOUS Opposite"],

  "TO CLAIM": ["ASSERT", "AVOW", "CONTEND", "PROCLAIM", "DECLARE"],
  "TO THINK DEEPLY": ["CONTEMPLATE", "DELIBERATE", "INTROSPECT", "MULL", "PENSIVE", "PONDER", "REFLECT", "RUMINATE"],
  "ENTER WITHOUT PERMISSION": ["ENCROACH", "INTRUDE", "OBTRUDE"],
  "TO IRRITATE": ["DISGRUNTLE", "EXASPERATE", "HARANGUE", "IRKSOME", "PEEVE", "VEX", "MAKE ANGRY"],
  "SECRET": ["CLANDESTINE", "COVERT", "FURTIVE", "SLY", "STEALTH", "SURREPTITIOUS", "DISCREET", "UNDERHANDED", "OVERT Opposite"],
  "UNCOVER A SECRET": ["UNEARTH", "UNRAVEL"],
  "EXAGGERATE": ["HYPERBOLE", "MAGNIFY", "UNDERPLAY Opposite", "UNDERSTATE Opposite", "UNDERREPORT Opposite"],
  "RESPECT": ["DEFERENCE", "EXALT", "REVERE", "VENERATE"],
  "IMITATE": ["EMULATE", "SIMULATE", "MIMIC Similar", "COMIC IMITATION"],
  "OFFENSIVE": ["LURID", "OBSCENE", "VULGAR", "SENSATIONAL", "LUSTY"],
  "GIVE UP": ["ABDICATE", "CEDE", "FORGO", "FORSAKE", "RELINQUISH", "RENOUNCE"],
  "EASILY AFFECTED": ["PRONE", "SUBJECT TO", "SUSCEPTIBLE", "VULNERABLE", "IMPERVIOUS Opposite", "IMMUNE Opposite"],
  "VARIETY": ["VARIED", "DIVERSITY", "ECLECTIC", "MULTIFACETED", "MULTIFARIOUS", "VARIEGATE", "VERSATILE", "PASTICHE"],
  "EXAMINE CAREFULLY": ["PERUSE", "PORE OVER", "SCRUTINIZE", "#BROWSE (not thorough)"],
  "TAKE AWAY FORCIBLY": ["APPROPRIATE", "EXPROPRIATE", "PREEMPT", "USURP", "INALIENABLE Opposite"],
  "FRIENDLY": ["AFFABLE", "AMIABLE", "AMICABLE", "CONGENIAL", "CONVIVIAL", "CORDIAL", "FRATERNIZE", "BEFRIEND", "ALOOF Opposite"],
  "ABOUT TO HAPPEN": ["IMMINENT", "IMPENDING"],
  "CARELESS": ["LAX", "NEGLIGENT", "REMISS", "STRINGENT Opposite"],
  "INSPIRING FEAR OR RESPECT": ["AWE", "FORMIDABLE", "REDOUBTABLE"],
  "REVEAL": ["DIVULGE", "TELLING", "CONCEAL Opposite"],
  "IRRITABLE": ["CANTANKEROUS", "CHAGRIN", "IRASCIBLE", "TESTINESS"],
  "HIDE": ["COVER", "DISGUISE", "CAMOUFLAGE", "CLOAK", "DISSEMBLE", "FEIGN", "GUISE", "INCOGNITO", "MASK", "SHROUD"],
  "DELAY": ["ADJOURN", "DEFER", "PROTRACT", "PROCRASTINATE", "POSTPONE"],
  "ATTRACT": ["ARRESTING", "CAPTIVATE", "ENAMORED", "ENTHRALL", "MESMERIZE", "SPELLBINDING", "ENNUI Opposite", "FASCINATE"],
  "ILLOGICAL": ["ABSURD", "ATYPICAL", "BIZARRE", "LUDICROUS", "OUTLANDISH", "PREPOSTEROUS", "UNCANNY", "STRANGE"],
  "FALSEHOOD": ["PERJURY", "PREVARICATION", "VERACITY Opposite", "FALSEHOOD"],
  "SHY": ["DIFFIDENCE", "RESERVED", "RETIRING", "TIMID", "INTROVERT"],
  "DISREPUTE": ["IGNOMINY", "INFAMY", "NOTORIOUS", "BAD REPUTATION"],
  "FEARFUL": ["COWER", "DAUNT", "PETRIFY", "SHRINK", "TREPIDATION", "LACKING COURAGE"],
  "UNINTENTIONALLY": ["INADVERTENTLY", "UNWITTINGLY"],
  "ACCUSE": ["ASPERSION", "DEFAME", "MALIGN", "OBLOQUY", "OPPROBRIUM", "SLANDER", "STIGMATIZATION", "VILIFY", "DEFAME"],
  "COUNTER-ATTACK": ["RETALIATE", "REPRISAL"],
  "ALERT": ["VIGILANT", "INATTENTIVE Opposite"],
  "REVENGE": ["VENGEANCE", "VINDICTIVE", "RETRIBUTION"],
  "EMBARRASS": ["ABASH", "DISCOMFIT", "MORTIFY"],
  "URGENT": ["EXIGENT", "PRESSING", "CRITICAL", "DEMANDING", "Exacting"],
  "FAKE": ["DECEPTIVE", "AUTHENTIC Opposite", "LEGITIMATE Opposite", "VERITABLE Opposite","COUNTERFEIT", "DUBIOUS", "ERRONEOUS", "FABRICATE", "FALLACIOUS", "PHONY", "SHAM", "SOPHISTRY", "SPURIOUS", "PROPAGANDA Similar","GENUINE Opposite", "FORGERY", "INSINCERE", "DEVIOUS"],
  "PLACING IN INFERIOR RANK": ["RELEGATE", "DEMOTE", "SUBORDINATION"],
  "BEGINNER": ["APPRENTICE", "NOVEL", "NOVICE", "ROOKIE", "INEXPERIENCED"],
  "PUZZLING": ["CONUNDRUM", "CRYPTIC", "ENIGMA", "INSCRUTABLE", "INTRIGUE"],
  "BRAVE": ["METTLESOME", "CHIVALRY", "DAUNTLESS", "GALLANT", "INTREPID", "UNDAUNTED", "VALOR"],
  "WIDESPREAD": ["EPIDEMIC", "PANDEMIC", "RAMPANT", "ENDEMIC Opposite", "RIFE"],
  "STORY": ["ANECDOTE", "NARRATIVE"],
  "FLUENT": ["ARTICULATE", "COHERENT", "ELOQUENT", "ENUNCIATE", "INEFFABLE Opposite", "CLEAR"],
  "NATIVE": ["INDIGENOUS", "EXOTIC Opposite", "LOCAL"],
  "CONTRADICT ITSELF": ["IRONY", "PARADOX", "IRONIC"],
  "GLOOMY": ["BLEAK", "SOMBER", "DARK"],


  "SPOTTED": ["BLEMISH", "TAINT", "TARNISH", "STAINED"],
  "BEST EXAMPLE": ["ARCHETYPE", "EMBODY", "EPITOME", "EXEMPLIFY", "PARADIGM", "PARAGON", "PERSONIFY"],
  "FORCE": ["COERCION", "COMPEL", "COMPULSION", "PRESS", "PUT PRESSURE"],
  "ARTIFICIAL": ["AFFECTED", "CONTRIVED", "MANNERED", "POSTURE", "PRETENTIOUS", "PRETENSE"],
  "INTELLIGENT": ["WISE", "ACUITY", "ACUMEN", "DISCERNING", "DISCRIMINATING", "INSIGHTFUL", "JUDICIOUS", "PERCEPTIVE","PERSPICACIOUS", "PRUDENT", "SAGACIOUS", "SAGE", "SHREWD Similar", "IMPOLITIC Opposite","CANNY Similar", "SIMPLETON Opposite", "OMNISCIENCE", "IMPRUDENT Opposite"],
  "IMPURE": ["ADULTERATE", "CONTAMINATE", "NOXIOUS", "TOXIC", "POISONOUS"],
  "PERSUADE": ["COGENT", "EXHORT", "INDUCE", "URGE", "WOO Similar", "COURT Similar", "HORTATORY"],
  "PLEAD": ["ENTREATY", "IMPLORE", "IMPORTUNE"],
  "PERSUADE WITH FLATTERY": ["CAJOLE", "COAX", "BLANDISHMENT"],
  "REQUIRED": ["NECESSITATED", "WARRANTED"],
  "SPOIL": ["DEFACE", "DISTORT", "IMPAIR", "DISFIGURE"],
  "RECOGNIZED": ["OBTAIN", "PREVAIL", "PREVALENT", "ESTABLISHED"],
  "TEMPT": ["ALLURE", "ENTICE", "LURE"],
  "PLOT": ["COLLUDE", "CONNIVE", "CONSPIRE", "SCHEME", "TACTIC", "TRICK"],
  "GET RID OF or CLEANSE": ["CATHARSIS", "EXPURGATE", "PURGE"],
  "NOT SACRED": ["CLERICAL Opposite", "SECULAR", "TEMPORAL", "WORLDLY"],
  "INBORN": ["INTRINSIC", "INNATE", "INHERENT", "ENTRENCHED", "CONGENITAL", "INGRAINED", "FIRMLY FIXED"],
  "AWARE": ["COGNIZANT", "OBLIVIOUS Opposite"],
  "TO SEE": ["BEHOLD", "DISCERN", "PERCEIVE", "IMPERCEPTIBLE Opposite"],
  "UNMATCHED": ["INIMITABLE", "PEERLESS", "UNIQUE"],
  "STUPID": ["IMBECILE", "INANE", "VACUOUS", "FOOLISH"],
  "SULKING": ["PEEVISH", "POUT", "SULLEN", "SURLY", "BAD-TEMPERED"],
  "PROVEN TO BE RIGHT": ["JUSTIFIABLE", "UNTENABLE Opposite", "INDEFENSIBLE Opposite"],
  "GO OFF - TRACK": ["ASTRAY", "CIRCUITOUS", "DIGRESS", "DISCURSIVE", "DIVERGENT", "TANGENTIAL"],
  "RIGHT TO VOTE": ["ENFRANCHISE", "SUFFRAGE"],
  "INSIGNIFICANT": ["MARGINAL", "MINUTE", "NEGLIGIBLE", "TRIFLE", "INCONSIDERABLE"],
  "EXCLUDE": ["OSTRACIZE", "SHUN", "TABOO", "FORBID"],
  "STRENGTHEN": ["BOLSTER", "BUTTRESS", "FORTIFY", "SUPPORT"],
  "TO INFER": ["CONSTRUE", "DEDUCE", "EXTRAPOLATE", "INDUCTIVE", "GENERALIZE"],
  "HINT": ["ALLUDE", "ALLUSION", "IMPLICIT", "TACIT", "BLATANT Opposite", "EXPLICIT Opposite", "CITE Opposite", "INDIRECT REFERENCE"],
  "HUGE": ["COLOSSAL", "GARGANTUAN", "GIGANTIC", "HUMONGOUS", "MONOLITHIC", "MONUMENTAL", "VOLUMINOUS", "CAPACIOUS"],
  "FRANK": ["CANDID", "CANDOR", "FORTHRIGHT", "VOCAL", "EQUIVOCATION Opposite", "BIG"],
  "GUESSWORK": ["CONJECTURE", "SURMISE", "HYPOTHETICAL", "EMPIRICAL Opposite", "SPECULATIVE", "PRESUMPTIVE", "EXPERIENTIAL Opposite", "UNPROVEN THEORY"],
  "SMALL": ["SLIGHT", "MINUSCULE", "INFINITESIMAL", "DWARF"],
  "HARSH": ["ACERBIC", "SHARP", "BITING", "ACRIMONIOUS", "CAUSTIC", "INCISIVE", "SCATHING", "EUPHEMISM Opposite"],
  "PREPARED": ["PRIMED"],
  "UNDERSTAND": ["APPREHEND", "ASSIMILATE", "COMPREHEND", "FATHOM", "INTELLIGIBLE", "ILLEGIBLE Opposite", "MISCONSTRUED Opposite"],
  "SYMPATHY": ["COMPASSION", "EMPATHY", "CALLOUS Opposite"],
  "WEAK": ["INTANGIBLE", "FRAGILE", "TENUOUS", "SUBSTANTIAL Opposite"],
  "TO DO HAPPILY (+)": ["ALACRITY", "OBLIGING", "GRUDGING Opposite"],
  "EASILY NOTICEABLE": ["PATENT", "CONSPICUOUS", "PROMINENT", "DISTINGUISHABLE"],
  "MINOR DIFFERENCES": ["NUANCES", "SUBTLE"],
  "REMOVE": [ "DESTROY", "ANNIHILATE", "DECIMATE", "EFFACE", "ERADICATE", "EXTERMINATE", "OBLITERATE", "PERISH", "RAZE", "INDELIBLE Opposite", "DEVASTATE", "EXCISE"],
  "MISTAKE": ["MISNOMER", "TACTLESS", "ACT DONE CARELESSLY"],
  "USED TO": ["HABITUATE", "INURE", "INVETERATE", "ACCUSTOMED", "WONT"],
  "PLACE SIDE BY SIDE": ["ADJACENT", "JUXTAPOSITION"],
  "FULLY SATISFIED": ["GRATIFY", "REPLETE", "SATIATE", "SUFFICE"],
  "DISRESPECTING SACRED THINGS": [ "BLASPHEMY", "DESECRATE", "IMPIOUS", "SACRILEGE", "CONSECRATE Opposite", "SACROSANCT Opposite", "ANOINT Opposite", "PIOUS Opposite"],
  "UNSTEADY": ["FALTER", "FLOUNDER", "FOUNDER", "FUMBLE"],
  "RESTRICT": ["STOP", "PREVENT", "DISSUADE", "CHECK", "DETER", "FORESTALL", "FRUSTRATE", "HINDER","IMPEDE", "IMPEDIMENT", "INHIBIT", "OBSTRUCT", "PRECLUDE", "THWART", "OCCLUDE", "STANCH", "PREEMPT", "OBVIATE"],
  "BAN": ["SANCTION", "DEPLATFORM"],
  "WITHOUT REAL POWER": ["FIGUREHEAD", "NOMINAL", "TITULAR"],
  "CARELESS": ["SHODDY", "SLOPPY", "UNKEMPT", "DIRTY"],
  "BLAMEWORTHY": ["CULPABLE", "REPREHENSIBLE", "GUILTY"],
  "ATTRACTIVE": ["ADORN", "EMBELLISH", "FLORID", "ORNATE", "RESPLENDENT", "DECORATIVE"],
  "OVER CONCERN": ["OFFICIOUS (-)", "SOLICITOUS", "HELPFUL"],
  "PUNISH": [ "CONDEMN", "CONVICT", "IMMURE", "INCARCERATE", "SENTENCE", "CONDONE Opposite"],
  "FREE FROM BLAME": ["ACQUIT", "EXONERATE", "VINDICATE"],
  "INSULTING WORDS": ["DEPRECATORY", "DEROGATORY", "PEJORATIVE"],
  "CANCEL": ["TAKE BACK", "ANNUL", "DISAVOW", "NULL", "RENEGE", "REPEAL", "REPUDIATE", "RETRACT", "REVOKE", "VOID"],
  "BARE": ["STARK", "BARREN"],
  "PHYSICALLY STRONG": ["ROBUST", "RUGGED", "STURDY", "VIGOROUS"],
  "DEAD END": ["IMPASSE", "STALEMATE"],
  "ACTIVATE": ["SPEED UP", "EXPEDITE", "FACILITATE", "KINDLE", "PRECIPITATE", "PROMPT", "PROPEL", "ACCELERATE", "STIMULATE"],
  "A VOTE": ["BALLOT", "REFERENDUM"],
  "THANKFUL or Similar BOUNDED": ["BEHOLDEN", "INDEBTED", "GRATEFUL", "GRATITUDE", "Similar OBLIGATED"],
  "OVERLY OBEDIENT": ["SERVILE", "SLAVISH", "SUBSERVIENT"],
  "TO BLAME": ["ALLEGE", "ALLEGATION", "IMPLICATE", "INCRIMINATE", "INDICT", "ACCUSE", "CHARGE"],
  "LEFT-OVER": ["REMNANT", "RESIDUAL", "TRACE", "VESTIGE", "Similar MODICUM"],
  "SUBSTITUTE": ["Similar MAKESHIFT (TEMPORARY)", "PROXY", "SURROGATE"]
};