const wordGroups = {
  "Sign": ["Forebode", "Foreshadow", "Ominous", "Premonition", "Warning"],
  "Causing fear": ["Daunting", "Intimidate", "Sinister"],
  "Flexible": ["Agile", "Lithe", "Supple"],
  "Attractive": ["Aesthetic", "Comely"],
  "Very Talented": ["Prodigy", "Precocious"],
  "Prediction": ["Anticipate", "Forecast", "Foresight", "Foresee", "Foretell", "Presage", "Prescience", "Prognosis"],
  "Very Angry": ["Enrage", "Fume","Incense", "Indignation", "Infuriate", "Irate", "Ire", "Livid", "Wrath"],
  "Detailed Knowledge": ["Intellectual", "Cerebral", "Erudite", "Enlightened","Enlightenment", "Pundit", "Refined", "Refinement"],
  "SkillFull": ["Adept", "Adroit", "Consummate", "Deft", "Dexterous", "Finesse","Proficient", "Prowess", "Inept Opposite", "Maladroit Opposite"],
  "Having Twist": ["Turn", "Complex", "Circuitous", "Convulated", "Complicated", "Interwined", "Involved", "Meander", "Tortuous"],
  "Inclination": ["Affinity", "Aptitude", "Bent", "Disposed", "Penchant", "Predilection", "Predisposition", "Proclivity", "Prospensity"],
  "Ineffective": ["Futile", "Ineffectual", "Efficacy Oppose", "Feckless Similar"],
  "Horryfing": ["Shocking", "Aghast", "Apalling", "Egregious", "Ghastly", "Gross", "Gruesome", "Heinous", "Hideous", "Horrendous", "Monstrous", "Morbid", "Unsightly", "Vile"],
  "Separate": ["Disjointed", "Polarize", "Segregate", "Connected Opposite", "Nexus Opposite"],
  "Avoid": ["Dodge", "Avert", "Circumvent", "Deflect", "Elude", "Elusive", "Evade", "Evasive", "Shirk", "Skirt", "Swerve", "Head-on Opposite", "Inevitable Opposite", "Unavoidable opposite"],
  "Awkward": ["Clumsy", "Fumble", "Gauche", "Gawky", "Ungainly"],
  "Optimistic": ["Buoyant", "Sanguine", "Upbeat"],
  "Be slow": ["Waste time", "Dilatory", "Linger", "Malinger"],
  "Instructive" : ["Didactic", "Pedantic", "Sophist"],
  "Spread": ["Diffuse", "Disseminate", "Promulgate", "Propagate"],
  "Excessive Flattery": ["Adulation", "Obsequious", "Sycophant"],
  "Bodily": ["Anatomical", "Corporeal", "Physiological"],
  "Hate": ["Animosity", "Antipathy", "Aversion", "Despicable", "Detest", "Loathe", "Repel", "Repugnant", "Repulsion"],
  "Old Fashioned": ["Antiquated", "Archaic", "Dated", "Obsolete", "Outmoded", "Quaint", "Outdated"],
  "Arranged in Time": ["Chronicle", "Chronological"],
  "Co-existing": ["Contemporary", "Simultaneous", "Erstwhile Opposite", "Anachronism Opposite"],
  "Cautious": ["Careful", "Risky Opposite","Caveat", "Circumspect", "Heedful", "Prudent", "Wary", "Folly Opposite", "Rash Opposite", "Reckless Opposite"],
  "Self-Satisfaction": ["Bask", "Complacent"],
  "Scolding": ["Admonish", "Berate", "Censure", "Chastise", "Rebuke", "Reprimand", "Reproach", "Upbraid"],
  "Criticize": ["Assail", "Castigate", "Decry", "Denounce", "Denunciation", "Epithet", "Excoriate", "Vituperative", "Invective"],
  "To Defeat": ["Pulverize", "Subjugate", "Vanquish", "Subdue", "Capitulate", "Surrender"],  
  "Rule": ["Doctrine", "Dogmas", "Ideology", "Mandate", "Tenets", "Principle", "Law", "Canons"],
  "Rebellious": ["Unconventional", "Dissident", "Heresy", "Heretical", "Heterodox", "Iconoclast", "Insurgent", "Insurrection", "Maverick", "Nonconformist", "Radical", "Renegade", "Revolutionary", "Subversive", "Conservative Opposite", "Conventional Opposite", "Orthodox Opposite", "Reactionary Opposite"],
  "To Stir Up": ["Revolt", "Incite", "Incendiary", "Instigate", "Provoke", "Sedition"],
  "Complain (Low Degree)": ["Captious", "Querulous"],
  "Danger": ["Jeopardy", "Peril", "Precarious", "Snare", "Risk"],
  "Bitter Feelings": ["Ill-Will", "Malevolence", "Malice", "Vicious", "Virulent"],
  "Troubled": ["Beset", "Beleaguered", "Plagued"],
  "Mock": ["Disrespect", "Banter", "Belittle", "Condescend", "Contempt", "Denigrate","Deride", "Disdain", "Disparage", "Jibe","Raillery", "Sarcastic", "Taunt", "Scorn", "Spurn"],
  "Praise": ["Acclaim", "Accolade", "Applaud", "Approbation", "Commendable", "Encomiastic", "Exalt", "Extol", "GLorify", "Hail", "Laud", "Lionize"],
  "Emphasize": ["Accentuate", "Foreground", "Underscore"],
  "Similarity": ["Analogy", "Antithetical Opposite", "Match"],
  "Coming Together": ["Coalesce", "Rally"],
  "Equality": ["Commensurate", "Parity", "Peers", "Tantamount", "Disparate Opposite", "Disparity Opposite"],
  "Agreement": ["Harmony", "Accord", "Concord", "Conformity", "Congruous", "Consensus", "Consonance", "Unanimity", "Understanding"],
  "Disagreement": ["Discord", "Discrepancy", "Dissonance", "Faction", "Incompatible", "Irreconcilable", "Veto"],
  "Split": ["Chasm", "Dichotomy", "Gulf", "Rift", "Schism", "Gap"],
  "Aggressive": ["Argumentative", "Belligerent", "Bellicose", "Contetious", "Disputatious", "Fractious", "Hostility", "Litigious", "Polemical", "Pugnacious", "Truculent"],
  "Argue": ["Fight", "Altercation", "Contend", "Row", "Scuffle", "Tiff", "Truce Opposite"],
  "Confused": ["Taken Aback", "Astound", "Baffle", "Bemuse", "Bewilder", "Confound", "Nonplussed", "Obfuscate", "Perplex", "Stupefy"],
  "Calm": ["Indifferent", "Apathetic", "Aplomb", "Composure", "Equanimity", "Impassive", "Imperturbable", "Nonchalant", "Phlegmatic", "Placid", "Serene", "Tranquil", "Staid", "Stoic"],
  "Disturbed": ["Agitated", "Disconcert", "Dismay", "Disquiet", "Distraught", "Faze", "Fluster", "Frenetic", "Frenzied", "Hysterical", "Implacable", "Perturb"],
  "Make Hostile": ["Alienate", "Antagonize", "Estrange"],
  "Include Everything": ["Comprehensive", "Encompass", "Expansive", "Inclusive", "Pervasive", "Exhaustive"],
  "Present Everywhere": ["Omnipresent", "Ubiquitous"],
  "Narrow Minded": ["Insular", "Myopic", "Parochial", "Provincial", "Regional"],
  "Biased": ["Partial", "Bigot", "Discriminatory", "Partisan", "Prejudiced", "Tendentious", "subjectivity"],
  "Unbiased": ["Impartial", "Detached", "Detachment", "Disinterested", "Dispassionate", "Egalitarian", "Equitable", "Even Handed", "Objectivity"],
  "Disrespectfully Casual": ["Non-Serious", "Blithe", "Flippant", "Frivolous","Frivolity", "Levity", "Grave Opposite", "Gravity Opposite"],
  "Cure": ["Antidote", "Panacea"],
  "Suppress": ["End", "Quell", "Quash", "Repress", "Scotch", "Subdue"],
  "Dominating": ["Absolute", "Authoritative", "Autocrat", "Despot", "Dictate","Doctrinaire", "Dogmatic", "Imperious", "Totalitarian", "Tyrant"],
  "Being Alike": ["Homogeneity", "Uniformity", "Heterogeneity Opposite"],
  "Thorough": ["Precise", "Conscientious", "Demanding", "Exacting", "Fastidious", "Meticulous", "Punctilious", "Scrupulous"],
  "Fussy": ["Nice", "Stickler", "Hard to Please"],
  "Not Thorough": ["Cursory", "Perfunctory", "Summarily", "Superficially"],
  "SHORT-LIVED": ["EPHEMERAL", "EVANESCENT", "FLEETING", "TRANSIENT", "TRANSITORY", "MOMENTARY"],
  "NEVER ENDING": ["NON STOP", "CHRONIC", "INCESSANT", "INEXORABLE", "INTERMINABLE", "PERENNIAL", "RELENTLESS"],
  "END": ["STOP", "TERMINATE", "CULMINATE", "CEASE", "CESSATION"],
  "IRREGULAR": ["PERIODICALLY", "FITFULLY", "INTERMITTENT", "OCCASIONAL", "SPORADIC"],
  "CALM DOWN": [ "TO MAKE LESS WORSE", "ALLAY", "ALLEVIATE", "AMELIORATE", "APPEASE", "ASSUAGE", "CONCILIATE", "EXTENUATING", "MITIGATE", "MOLLIFY", "PACIFY", "PLACATE", "PROPITIATE", "SOLACE", "TEMPER", "EXACERBATE Opposite"],
  "LACKING ENERGY": ["JADED", "LACKADAISICAL", "LACKLUSTER", "LANGUID", "LASSITUDE", "LETHARGIC", "LISTLESS", "LAZY"],
  "HARDWORKING": ["ASSIDUOUS", "DILIGENT", "INDUSTRIOUS", "PAINSTAKING", "TOIL"],
  "HAPPY": ["JOYOUS", "BEAM", "ECSTASY", "ELATED", "EUPHORIA", "EXHILARATION", "EXULTANT", "GAIETY", "JOVIAL", "REGALE", "UPROARIOUS"],
  "UNIMPORTANT": ["TRIVIAL", "EXPENDABLE", "FRINGE", "INCIDENTAL", "INCONSEQUENTIAL", "MARGINALIZATION", "PERIPHERAL"],
  "SAD": ["ANGUISH", "BEREAVED", "BLEAK", "CRESTFALLEN", "DEJECTED", "DESOLATE", "DESPONDENT", "LAMENT", "MELANCHOLY", "WOE", "PATHOS", "POIGNANT", "DESPAIR", "DEPRESSED"],
  "ENTHUSIASTIC": [ "EXCITED", "ARDOR", "ARDENT", "AVID", "DYNAMIC", "EBULLIENT", "EFFERVESCENT", "EXUBERANT", "FERVENT/FERVOR", "IMPASSIONED", "VIVACIOUS", "ZEALOUS", "ZEST", "DAMPEN Opposite", "TEPID Opposite", "RHAPSODY Similar"],
  "UNUSUAL": ["EXCEPTION", "ABERRATION", "ANOMALY", "DEVIATE"],
  "ORDINARY": ["UNORIGINAL","BANAL", "CLICHE", "COMMONPLACE", "DERIVATIVE", "HACKNEY", "HUMDRUM", "MUNDANE", "PEDESTRIAN", "PLATITUDE", "QUOTIDIAN", "TRITE", "UNREMARKABLE", "BROMIDE", "PROSAIC"],
  "DIFFICULT TO UNDERSTAND": ["OPAQUE", "ABSTRACT", "ABSTRUSE", "ARCANE", "ESOTERIC", "MYSTICAL", "OBSCURE", "RECONDITE", "PROFOUND" ,"PROFUNDITY", "PERSPICUOUS Opposite"],
  "CRUCIAL": ["SIGNIFICANT", "CORE", "FOREMOST", "IMPERATIVE", "INDISPENSABLE", "MANDATORY", "MOMENTOUS", "PIVOTAL", "SALIENT"],
  "ENERGIZING": ["INVIGORATING", "REVITALIZING"],
  "INACTIVE": ["DORMANT", "STAGNANT"],
  "BORING": ["VAPID", "BLAND", "INSIPID", "DRAB", "DULL"],
  "REPETITIOUS THUS BORING": ["MONOTONOUS", "TEDIOUS", "PLOD"],
  "UNWILLING TO SPEND": ["SPENDING WISELY", "CLOSEFISTED", "MISERLY", "PARSIMONIOUS", "STINGY", "TIGHTFISTED", "THRIFT Similar", "FRUGAL Similar", "HUSBANDRY Similar", "ECONOMICAL Similar", "ECONOMY Similar"],
  "COMBINE": ["AMALGAMATE", "COALITION", "MELD", "SYNTHESIS", "INTEGRATE", "PAIRING"],
  "VERY LESS": ["EXIGUOUS", "MEAGER", "PUNY", "SCANTY", "SPARSE", "SCARCE"],
  "UNCLEAR IN MEANING": ["AMBIVALENT", "AMBIGUOUS", "EQUIVOCAL"],
  "EXCESSIVE PATRIOTISM": ["FANATIC", "ZEALOT", "IDEALOGUE"],
  "REMEMBERING THE PAST": ["EVOCATIVE", "HINDSIGHT", "NOSTALGIA", "REMINISCENCE", "RETROSPECT", "WISTFUL"],
  "LUCKY": ["FORTUITOUS", "OPPORTUNE", "PROPITIOUS", "SERENDIPITY", "HAPLESS Opposite", "UNLUCKY Opposite"],
  "WEALTHY": ["OPULENT", "AFFLUENT"],
  "PAIN": ["SUFFERING", "ADVERSITY", "AFFLICTIONS", "MISHAP", "ORDEALS", "TRIALS", "TRIBULATION"],
  "ROUTINE BEHAVIOR": ["OBTAIN", "WONT"],
  "RELEVANT": ["GERMANE", "PERTINENT"],
  "EXCESS": ["ABOUND", "COPIOUS", "MYRIAD", "PLETHORA", "PROFUSE", "PROLIFIC", "STEEPED", "SURFEIT", "SURGE"],
  "REDUCE": ["CONSTRICT", "CONTRACT", "CURTAIL", "DWINDLE", "FLAG", "WANE", "RETRENCH", "RESTRICT"],
  "INCREASE": ["ACCRETION", "AGGRANDIZE", "AUGMENT", "BALLOON", "DILATE", "ENHANCE", "MOUNTING", "PROLIFERATE", "WAX", "BURGEON Similar", "MAGNIFY"],
  "EXPLAIN TOO MUCH": ["BELABOR", "UNDERSTATEMENT Opposite"],
  "LESSEN IN INTENSITY": ["ABATE", "EBB", "RECEDE", "SUBSIDE"],
  "VERY HIGH PRICE": ["EXORBITANT", "PROHIBITIVE"],
  "CANNOT BE DEFEATED": ["IMPERVIOUS", "INDOMITABLE", "INVINCIBLE", "IMPENETRABLE"],
  "SHORTAGE": ["DEFICIT", "PAUCITY", "WANTING", "DEVOID", "DEPRIVED", "LACKING"],
  "POOR": ["IMPECUNIOUS", "IMPOVERISH", "INDIGENT"],
  "SPEND LAVISHLY": ["PRODIGAL", "PROFLIGATE", "SPENDTHRIFT", "SQUANDER", "EXTRAVAGANCE", "LAVISH", "WASTE"],
  "FAREWELL": ["VALEDICTORY", "PARTING", "MIGRATION", "TO GO AWAY"],
  "TO RISE BEYOND": ["TRANSCEND", "SURPASS", "OUTSTRIP"],
  "NERVOUS": ["RESTIVE", "SKITTISH", "RESTLESS"],
  "COMPETITIVENESS": ["AMBITIOUS", "OPPORTUNISM", "ASPIRATION"],
  "SURE": ["CERTAIN", "ABSOLUTE", "CATEGORICAL", "CERTITUDE", "CONVICTION", "EMPHATIC", "INCONTROVERTIBLE", "UNQUALIFIED", "CONTINGENT Opposite", "PROVISIONAL Opposite", "INCONCLUSIVE Opposite", "QUALIFIED Opposite", "CONDITIONAL Opposite"],
  "RELATED": ["KINDRED", "AFFILIATED"],


  "PLEASANT SOUNDING": ["EUPHONY", "MELODIOUS", "MELLIFLUOUS"],
  "GREED": ["AVARICE", "COVETOUS", "GLUTTON (food)", "VORACIOUS"],
  "OVERLY NOISY": ["CACOPHONY", "CLAMOR", "CLANGOR", "DISCORDANT", "RAUCOUS", "STRIDENT", "VOCIFEROUS", "INAUDIBLE Opposite"],
  "SUPPORTER": ["ADVOCATE", "ALLY", "CHAMPION", "ENDORSE", "ESPOUSE", "LOBBYIST", "PROPONENT", "PROTAGONIST", "ADVERSARY Opposite", 
  "ANTAGONIST Opposite", "DETRACTOR Opposite", "FOE Opposite", "IMPUGN Opposite", "INIMICAL Opposite", "NEMESIS Opposite"],
  "RESOLUTE": ["ENDURE", "IMMUTABLE", "INDEFATIGABLE", "PERSEVERE", "PERSISTENCE", "RESOLUTE", "STEADFAST", "TENACIOUS"],
  "STUBBORN": ["OBDURATE", "ADAMANT", "DEFIANT", "INCORRIGIBLE", "INTRACTABLE", "INTRANSIGENT", "OBSTINATE", "PERVERSE", "RECALCITRANT", "REFRACTORY"],
  "ACCEPT": ["ACCEDE", "ACQUIESCE", "AMENABLE", "ASSENT", "COMPLIANT", "COMPLY", "CONCEDE", "PLIANT", "RELENT", "SUCCUMB", "YIELD", "DOCILE (easily controlled)", "MALLEABLE (easily controlled)", "AGREE", "GIVE IN"],
  "TO MAKE UP": ["CONCOCT", "DEVISE", "FORMULATE", "CONJURE", "CREATE"],
  "PLANNED": ["AD-HOC Opposite", "CALCULATED", "DELIBERATE", "FORETHOUGHT", "INTENTIONAL", "PREMEDITATED", "STUDIED", "EXTEMPORANEOUS Opposite", "IMPETUOUS Opposite", "IMPROMPTU Opposite", "IMPROVISE Opposite"],
  "EXTRA HENCE UNNECESSARY": ["EXTRANEOUS", "REDUNDANT", "SUPERFLUOUS"],
  "TO PROVE FALSE": ["BELIE", "DEBUNK", "DISCREDIT", "EXPOSTULATE", "REBUT", "REFUTE"],
  "PROFITABLE": ["REMUNERATIVE", "LUCRATIVE"],
  "TO OBJECT": ["DEFY", "DEMUR", "DISSENT", "TAKE ISSUE WITH"],
  "VILLAGE-LIKE": ["BUCOLIC", "PASTORAL", "RUSTIC"],
  "FAMOUS": ["EMINENT", "LUMINARY", "PRE-EMINENT", "PREEMINENCE", "STATURE"],
  "BREAK A RULE": ["BREACH", "FLOUT", "TRANSGRESS", "ABIDE Opposite", "ADHERE Opposite", "INFRACTION"],
  "FICKLE": ["ARBITRARY", "CAPRICIOUS", "ERRATIC", "INCONSISTENT", "IRRESOLUTE", "MERCURIAL", "OSCILLATE", "SWAY", "TEMPERAMENTAL", "VOLATILE", "WAFFLE", "WAVER", "WHIMSICAL"],
  "INDIRECT EXPERIENCE": ["VICARIOUS"],
  "CONFIRM": ["ASCERTAIN", "AFFIRM", "CORROBORATE", "RATIFY", "SUBSTANTIATE", "TESTIFY", "TESTIMONY", "VALIDATE", "UNFOUNDED Opposite"],
  "SEVERE": ["ACUTE", "AUSTERE"],
  "CLOTHING": ["SARTORIAL", "RAIMENT"]
};