const wordMeaning = {
  "Forebode": "To predict or indicate something bad will happen",
  "Foreshadow": "To give a hint or warning of a future event",
  "Ominous": "Suggesting that something bad is going to happen",
  "Premonition": "A strong feeling that something is about to happen",
  "Warning": "A statement or sign that something bad might happen",
  "Daunting": "Seeming difficult to deal with; intimidating",
  "Intimidate": "To frighten or overawe someone, especially to make them do what you want",
  "Sinister": "Giving the impression that something harmful or evil is happening",
  "Agile": "Able to move quickly and easily",
  "Lithe": "Thin, supple, and graceful in movement",
  "Supple": "Bending and moving easily and gracefully",
  "Aesthetic": "Concerned with beauty or the appreciation of beauty",
  "Comely": "Pleasant to look at; attractive",
  "Prodigy": "A young person with exceptional abilities or talent.",
  "Precocious": "Having developed certain abilities at an earlier age than usual.",
  "Anticipate": "To expect or predict something before it happens.",
  "Forecast": "To predict or estimate a future event or trend.",
  "Foresight": "The ability to predict or prepare for the future.",
  "Foresee": "To be aware of or predict a future event.",
  "Foretell": "To predict something in the future, usually through intuition or supernatural means.",
  "Presage": "A sign or warning that something will happen, usually bad.",
  "Prescience": "The fact of knowing something before it takes place; foresight.",
  "Prognosis": "A medical prediction about the likely outcome of a disease or condition.",
  "Enrage": "To make someone extremely angry.",
  "Fume": "To show irritation or anger visibly.",
  "Incense": "To make someone very angry.",
  "Indignation": "Anger or annoyance provoked by unfair treatment.",
  "Infuriate": "To make someone extremely angry or furious.",
  "Irate": "Feeling or showing great anger.",
  "Ire": "Intense anger.",
  "Livid": "Furiously angry.",
  "Wrath": "Extreme or violent anger.",
  "Intellectual": "Relating to deep thinking or knowledge.",
  "Cerebral": "Involving intellect rather than emotion.",
  "Erudite": "Having or showing great knowledge.",
  "Enlightened": "Free from ignorance and aware.",
  "Enlightenment": "State of gaining spiritual or intellectual insight.",
  "Pundit": "An expert in a particular field who gives opinions.",
  "Refined": "Showing sophisticated and polished behavior or knowledge.",
  "Refinement": "The improvement or sophistication of something.",
  "Adept": "Very skilled or proficient at something.",
  "Adroit": "Clever or skillful in using the hands or mind.",
  "Consummate": "Showing a high degree of skill.",
  "Deft": "Quick and skillful in movement or action.",
  "Dexterous": "Skillful, especially with hands.",
  "Finesse": "Delicate skill in handling difficult situations.",
  "Proficient": "Competent or skilled in doing something.",
  "Prowess": "Exceptional skill or ability.",
  "Inept Opposite": "Lacking skill or ability; clumsy.",
  "Maladroit Opposite": "Ineffective or bungling; unskillful.",
  "Turn": "To move in a circular direction",
  "Complex": "Complicated and hard to understand",
  "Circuitous": "Longer than the most direct way",
  "Convoluted": "Extremely complex and difficult to follow",
  "Complicated": "Not easy to understand or deal with",
  "Intertwined": "Twisted together or closely connected",
  "Involved": "Difficult to understand; complicated",
  "Meander": "To follow a winding path",
  "Tortuous": "Full of twists and turns",
  "Affinity": "A natural liking for something",
  "Aptitude": "Natural ability to do something",
  "Bent": "Natural talent or tendency",
  "Disposed": "Inclined or willing",
  "Penchant": "A strong liking or tendency",
  "Predilection": "A preference or special liking",
  "Predisposition": "A tendency to behave in a certain way",
  "Proclivity": "A natural inclination or tendency",
  "Propensity": "An inclination or natural tendency",
  "Futile": "Incapable of producing any result",
  "Ineffectual": "Not producing the desired effect",
  "Efficacy": "The ability to produce a result",
  "Feckless": "Lacking initiative or effectiveness",
  "Shocking": "Causing intense surprise or disgust",
  "Aghast": "Filled with horror or shock",
  "Appalling": "Causing shock or dismay",
  "Egregious": "Outstandingly bad",
  "Ghastly": "Horrible or frightful",
  "Gross": "Very unpleasant or disgusting",
  "Gruesome": "Causing horror or disgust",
  "Heinous": "Shockingly evil",
  "Hideous": "Extremely ugly or disgusting",
  "Horrendous": "Extremely unpleasant or horrifying",
  "Monstrous": "Inhumanly cruel or evil",
  "Morbid": "Gruesome or related to death",
  "Unsightly": "Not pleasant to look at",
  "Vile": "Extremely unpleasant or morally bad",
  "Disjointed": "Lacking connection or coherence.",
  "Polarize": "To divide into opposing groups.",
  "Segregate": "To separate or set apart from others.",
  "Connected": "Joined or linked together. (Opposite of Disjointed)",
  "Nexus": "A connection or series of connections. (Opposite of Disjointed)",
  "Dodge": "To move quickly to avoid something.",
  "Avert": "To turn away or prevent something bad.",
  "Circumvent": "To find a way around an obstacle.",
  "Deflect": "To cause something to change direction.",
  "Elude": "To escape from danger or difficulty.",
  "Elusive": "Difficult to find or catch.",
  "Evade": "To escape or avoid, especially by cleverness.",
  "Evasive": "Tending to avoid commitment or revealing information.",
  "Shirk": "To avoid responsibilities or duties.",
  "Skirt": "To go around the edge of something; avoid.",
  "Swerve": "To turn suddenly to avoid something.",
  "Head-on": "Direct confrontation. (Opposite)",
  "Inevitable": "Certain to happen. (Opposite of avoidable)",
  "Unavoidable": "Impossible to avoid. (Opposite of avoid)",
  "Clumsy": "Lacking coordination or grace.",
  "Fumble": "To handle clumsily or drop.",
  "Gauche": "Socially awkward or lacking grace.",
  "Gawky": "Physically awkward and ungainly.",
  "Ungainly": "Awkward or clumsy in movement or shape.",
  "Buoyant": "Cheerful and optimistic.",
  "Sanguine": "Confident and hopeful, especially in a bad situation.",
  "Upbeat": "Positive and cheerful in mood or tone.",
  "Waste time": "To use time inefficiently or without purpose.",
  "Dilatory": "Slow to act; intended to delay.",
  "Linger": "To stay in a place longer than necessary.",
  "Malinger": "To pretend to be ill to avoid work or duty.",
  "Didactic": "Intended to teach, especially in a moralizing way.",
  "Pedantic": "Overly concerned with rules or minor details.",
  "Sophist": "A person who uses clever but misleading reasoning.",
  "Diffuse": "To spread widely or thinly.",
  "Disseminate": "To spread information or ideas widely.",
  "Promulgate": "To make known by open declaration.",
  "Propagate": "To spread or promote an idea widely.",
  "Adulation": "Excessive praise or flattery.",
  "Obsequious": "Excessively obedient or attentive to gain favor.",
  "Sycophant": "A person who flatters to gain advantage.",
  "Anatomical": "Relating to the bodily structure of organisms.",
  "Corporeal": "Relating to the physical body.",
  "Physiological": "Relating to the functions of living organisms.",
  "Animosity": "Strong hostility or hatred.",
  "Antipathy": "A deep-seated feeling of dislike.",
  "Aversion": "A strong dislike or disinclination.",
  "Despicable": "Deserving hatred and contempt.",
  "Detest": "To strongly dislike or hate.",
  "Loathe": "To feel intense dislike or disgust.",
  "Repel": "To drive or force back; to be distasteful.",
  "Repugnant": "Extremely distasteful or unacceptable.",
  "Repulsion": "A feeling of intense disgust or aversion.",
  "Antiquated": "Old-fashioned or outdated.",
  "Archaic": "Very old or old-fashioned.",
  "Dated": "Out of date; no longer in style.",
  "Obsolete": "No longer produced or used; outdated.",
  "Outmoded": "Not modern; not in fashion anymore.",
  "Quaint": "Attractively old-fashioned or unusual.",
  "Outdated": "No longer current or in use.",
  "Chronicle": "A factual written account of events in order.",
  "Chronological": "Arranged according to the order of time.",
  "Contemporary": "Living or occurring at the same time.",
  "Simultaneous": "Occurring at the same moment.",
  "Erstwhile Opposite": "Former (opposite of current).",
  "Anachronism Opposite": "Something out of its time period (opposite of contemporary).",
  "Careful": "Taking caution to avoid mistakes or harm.",
  "Risky Opposite": "Involving danger or potential loss (opposite of cautious).",
  "Caveat": "A warning or cautionary detail.",
  "Circumspect": "Wary and unwilling to take risks.",
  "Heedful": "Paying careful attention to something.",
  "Prudent": "Acting with care and thought for the future.",
  "Wary": "Feeling or showing caution about dangers.",
  "Folly Opposite": "Lack of good sense (opposite of wise).",
  "Rash Opposite": "Acting without thinking (opposite of careful).",
  "Reckless Opposite": "Without regard for consequences (opposite of cautious).",
  "Bask": "To take pleasure in warmth or glory.",
  "Complacent": "Self-satisfied and unaware of possible dangers.",
  "Admonish": "To warn or reprimand gently.",
  "Berate": "To scold or criticize angrily.",
  "Censure": "Express severe disapproval.",
  "Chastise": "To reprimand harshly.",
  "Rebuke": "To express sharp disapproval.",
  "Reprimand": "A formal expression of disapproval.",
  "Reproach": "To express disappointment or disapproval.",
  "Upbraid": "To scold or criticize severely.",
  "Assail": "To attack violently or criticize strongly.",
  "Castigate": "To reprimand someone severely.",
  "Decry": "To publicly denounce.",
  "Denounce": "To condemn openly.",
  "Denunciation": "Public condemnation of someone or something.",
  "Epithet": "A descriptive phrase often showing criticism.",
  "Excoriate": "To criticize harshly and publicly.",
  "Vituperative": "Bitter and abusive.",
  "Invective": "Insulting or abusive language.",
  "Pulverize": "To crush or defeat completely.",
  "Subjugate": "To bring under control by force.",
  "Vanquish": "To defeat thoroughly.",
  "Subdue": "To overcome or bring under control.",
  "Capitulate": "To surrender after resistance.",
  "Surrender": "To give up to an opponent or authority.",
  "Doctrine": "A set of beliefs held by a group.",
  "Dogmas": "Principles laid down by an authority as true.",
  "Ideology": "A system of ideas and ideals.",
  "Mandate": "An official order or command.",
  "Tenets": "Principles or beliefs, especially religious or philosophical.",
  "Principle": "A fundamental truth or belief.",
  "Law": "A rule established by authority.",
  "Canons": "General laws or rules.",
  "Unconventional": "Not based on or conforming to what is generally done.",
  "Dissident": "A person who opposes official policy.",
  "Heresy": "Belief contrary to orthodox doctrine.",
  "Heretical": "Holding a belief against established doctrine.",
  "Heterodox": "Not conforming with accepted standards or beliefs.",
  "Iconoclast": "A person who attacks traditional beliefs.",
  "Insurgent": "A rebel or revolutionary.",
  "Insurrection": "A violent uprising against authority.",
  "Maverick": "An independent-minded person.",
  "Nonconformist": "Someone who does not follow established customs.",
  "Radical": "Advocating thorough or complete political reform.",
  "Renegade": "One who deserts or betrays an organization.",
  "Revolutionary": "Involving or causing a complete change.",
  "Subversive": "Intended to undermine authority.",
  "Conservative Opposite": "Resistant to change or innovation (opposite of radical).",
  "Conventional Opposite": "Following traditional forms (opposite of unconventional).",
  "Orthodox Opposite": "Conforming to traditional beliefs (opposite of heretical).",
  "Reactionary Opposite": "Opposing political or social progress (opposite of progressive).",
  "Revolt": "To rise against authority or control.",
  "Incite": "To provoke or stir up action.",
  "Incendiary": "Tending to stir up conflict or fire.",
  "Instigate": "To initiate or provoke an action or event.",
  "Provoke": "To stimulate a reaction, often anger.",
  "Sedition": "Conduct inciting rebellion against authority.",
  "Captious": "Tending to find fault in trivial matters.",
  "Querulous": "Complaining in a whining manner.",
  "Jeopardy": "Exposure to danger or risk.",
  "Peril": "Serious and immediate danger.",
  "Precarious": "Uncertain and likely to fall or collapse.",
  "Snare": "A trap for catching someone or something.",
  "Risk": "A situation involving exposure to danger.",
  "Ill-Will": "Hostile or unfriendly feelings.",
  "Malevolence": "Wishing harm to others.",
  "Malice": "The intention to harm or do evil.",
  "Vicious": "Deliberately cruel or violent.",
  "Virulent": "Extremely harmful or hostile.",
  "Beset": "To trouble or threaten persistently.",
  "Beleaguered": "Suffering or troubled from difficulties.",
  "Plagued": "To be constantly troubled or distressed.",
  "Disrespect": "Lack of respect or courtesy.",
  "Banter": "Playful and friendly exchange of teasing remarks.",
  "Belittle": "To make someone or something seem less important.",
  "Condescend": "To talk down to someone.",
  "Contempt": "The feeling that something is worthless.",
  "Denigrate": "To unfairly criticize or belittle.",
  "Deride": "To ridicule or mock.",
  "Disdain": "The feeling that something is unworthy of respect.",
  "Disparage": "To belittle or undervalue.",
  "Jibe": "An insulting or mocking remark.",
  "Raillery": "Good-humored teasing.",
  "Sarcastic": "Using irony to mock or convey contempt.",
  "Taunt": "To provoke or challenge with insults.",
  "Scorn": "A feeling of disdain or contempt.",
  "Spurn": "To reject with disdain.",
  "Acclaim": "Public praise and approval.",
  "Accolade": "An award or privilege granted as an honor.",
  "Applaud": "To show approval by clapping or cheering.",
  "Approbation": "Approval or praise.",
  "Commendable": "Deserving praise.",
  "Encomiastic": "Praising enthusiastically.",
  "Exalt": "To praise or raise highly.",
  "Extol": "To praise enthusiastically.",
  "GLorify": "To honor or praise highly.",
  "Hail": "To acclaim or greet enthusiastically.",
  "Laud": "To praise highly.",
  "Lionize": "To treat someone as a celebrity.",
  "Accentuate": "To make something more noticeable.",
  "Foreground": "To highlight or emphasize.",
  "Underscore": "To emphasize or stress.",
  "Analogy": "A comparison showing similarity.",
  "Antithetical Opposite": "Directly opposed or contrasted.",
  "Match": "Something equal or similar to another.",
  "Coalesce": "To come together to form one mass or whole.",
  "Rally": "To come together for a common purpose.",
  "Commensurate": "Equal in size, extent, or degree.",
  "Parity": "The state of being equal.",
  "Peers": "People of equal standing or rank.",
  "Tantamount": "Equivalent in value or significance.",
  "Disparate Opposite": "Fundamentally different; not equal.",
  "Disparity Opposite": "A lack of equality or similarity.",
  "Harmony": "A pleasing arrangement or agreement.",
  "Accord": "Agreement or harmony between people or groups.",
  "Concord": "Formal agreement or harmony.",
  "Conformity": "Compliance with standards or rules.",
  "Congruous": "In agreement or harmony.",
  "Consensus": "General agreement among a group.",
  "Consonance": "Agreement or compatibility between opinions or actions.",
  "Unanimity": "Complete agreement by everyone involved.",
  "Understanding": "Mutual comprehension or agreement.",
  "Discord": "Lack of agreement or harmony.",
  "Discrepancy": "A difference or inconsistency.",
  "Dissonance": "Lack of harmony or agreement.",
  "Faction": "A dissenting group within a larger one.",
  "Incompatible": "Not able to exist or work together.",
  "Irreconcilable": "Impossible to reconcile or bring into harmony.",
  "Veto": "The power to reject or forbid decisions.",
  "Chasm": "A deep division or separation.",
  "Dichotomy": "A division into two contrasting parts.",
  "Gulf": "A wide separation between people or ideas.",
  "Rift": "A break in friendly relations.",
  "Schism": "A split or division between strongly opposed parties.",
  "Gap": "An empty space or break in continuity.",
  "Argumentative": "Prone to arguing.",
  "Belligerent": "Hostile and aggressive.",
  "Bellicose": "Demonstrating aggression or eagerness to fight.",
  "Contetious": "Causing or likely to cause an argument.",
  "Disputatious": "Fond of or causing heated arguments.",
  "Fractious": "Irritable and quarrelsome.",
  "Hostility": "Unfriendly or aggressive behavior.",
  "Litigious": "Prone to engaging in lawsuits or disputes.",
  "Polemical": "Involving strong verbal or written attacks.",
  "Pugnacious": "Eager or quick to argue or fight.",
  "Truculent": "Aggressively defiant or hostile.",
  "Fight": "A violent or verbal confrontation.",
  "Altercation": "A noisy or heated argument.",
  "Contend": "To struggle or argue for something.",
  "Row": "A noisy dispute or quarrel.",
  "Scuffle": "A short, confused fight or struggle.",
  "Tiff": "A small or petty argument.",
  "Truce Opposite": "Conflict or continued fighting.",
  "Taken Aback": "Surprised or confused.",
  "Astound": "To shock or greatly surprise.",
  "Baffle": "To totally bewilder or confuse.",
  "Bemuse": "To puzzle, confuse, or bewilder.",
  "Bewilder": "To cause confusion.",
  "Confound": "To confuse or surprise.",
  "Nonplussed": "Bewildered or unsure how to respond.",
  "Obfuscate": "To make something unclear or confusing.",
  "Perplex": "To cause someone to feel baffled.",
  "Stupefy": "To shock or stun into confusion.",
  "Indifferent": "Having no particular interest or sympathy.",
  "Apathetic": "Showing or feeling no interest.",
  "Aplomb": "Self-confidence, especially in a demanding situation.",
  "Composure": "Calmness of mind or manner.",
  "Equanimity": "Mental calmness, especially under stress.",
  "Impassive": "Not showing emotion.",
  "Imperturbable": "Unable to be upset or excited.",
  "Nonchalant": "Calm and relaxed, not showing anxiety.",
  "Phlegmatic": "Having an unemotional and calm disposition.",
  "Placid": "Not easily upset or excited.",
  "Serene": "Calm, peaceful, and untroubled.",
  "Tranquil": "Free from disturbance; calm.",
  "Staid": "Serious, quiet, and steady in character.",
  "Stoic": "Enduring pain or hardship without showing emotion.",
  "Agitated": "Feeling or appearing troubled or nervous.",
  "Disconcert": "To unsettle or disturb.",
  "Dismay": "Sudden disappointment or anxiety.",
  "Disquiet": "A feeling of anxiety or unease.",
  "Distraught": "Deeply upset or agitated.",
  "Faze": "To disturb or disconcert.",
  "Fluster": "To make someone agitated or confused.",
  "Frenetic": "Fast and energetic in a wild or uncontrolled way.",
  "Frenzied": "Wildly excited or uncontrolled.",
  "Hysterical": "Exhibiting uncontrollable emotion or excitement.",
  "Implacable": "Unable to be calmed or appeased.",
  "Perturb": "To disturb or worry someone.",
  "Alienate": "To cause someone to feel isolated or estranged.",
  "Antagonize": "To cause someone to become hostile.",
  "Estrange": "To turn someone into a stranger or alienate them.",
  "Comprehensive": "Including all or nearly all elements or aspects.",
  "Encompass": "To include or surround completely.",
  "Expansive": "Covering a wide area in scope.",
  "Inclusive": "Not excluding any person or group.",
  "Pervasive": "Spreading widely throughout an area or group.",
  "Exhaustive": "Fully comprehensive and thorough.",
  "Omnipresent": "Present everywhere at the same time.",
  "Ubiquitous": "Found everywhere.",
  "Insular": "Narrow-minded or isolated in outlook.",
  "Myopic": "Lacking foresight or broad understanding.",
  "Parochial": "Having a limited or narrow outlook.",
  "Provincial": "Unsophisticated or narrow-minded in views.",
  "Regional": "Related to a particular region, often limited in scope.",
  "Partial": "Biased or showing favoritism.",
  "Bigot": "A person strongly and unfairly prejudiced.",
  "Discriminatory": "Showing unfair treatment or bias.",
  "Partisan": "Strongly supporting a side, often without considering others.",
  "Prejudiced": "Having a preconceived opinion not based on reason.",
  "Tendentious": "Promoting a particular cause or bias.",
  "subjectivity": "Influenced by personal feelings or opinions.",
  "Impartial": "Treating all rivals equally; unbiased.",
  "Detached": "Not influenced by emotions; objective.",
  "Detachment": "State of being unbiased or uninvolved.",
  "Disinterested": "Free from bias or self-interest.",
  "Dispassionate": "Not influenced by strong emotion.",
  "Egalitarian": "Believing in equal rights for all.",
  "Equitable": "Fair and impartial.",
  "Even Handed": "Treating all sides fairly and equally.",
  "Objectivity": "Judging without bias or emotion.",
  "Non-Serious": "Lacking seriousness or gravity.",
  "Blithe": "Carefree and unconcerned.",
  "Flippant": "Lacking proper respect or seriousness.",
  "Frivolous": "Not having serious purpose or value.",
  "Frivolity": "Lack of seriousness or sense.",
  "Levity": "Humor or lack of seriousness.",
  "Grave Opposite": "Lacking seriousness; not solemn.",
  "Gravity Opposite": "Marked by lightness; not serious.",
  "Antidote": "A remedy to counteract poison or disease.",
  "Panacea": "A solution for all problems or diseases.",
  "End": "To bring something to a close.",
  "Quell": "To suppress or subdue forcibly.",
  "Quash": "Reject or put an end to forcefully.",
  "Repress": "To subdue or hold back by force.",
  "Scotch": "To decisively put an end to.",
  "Subdue": "To overcome or bring under control.",
  "Absolute": "Unrestricted and complete.",
  "Authoritative": "Commanding and self-confident.",
  "Autocrat": "A ruler with absolute power.",
  "Despot": "A cruel and oppressive ruler.",
  "Dictate": "To impose or command forcefully.",
  "Doctrinaire": "Imposing a doctrine without regard to practicality.",
  "Dogmatic": "Strongly expressing beliefs as if they were facts.",
  "Imperious": "Assuming power without justification.",
  "Totalitarian": "A system with centralized absolute control.",
  "Tyrant": "A cruel and oppressive leader.",
  "Homogeneity": "The quality of being uniform or similar.",
  "Uniformity": "Consistency or sameness.",
  "Heterogeneity Opposite": "The opposite of diversity; sameness.",
  "Precise": "Exact and accurate.",
  "Conscientious": "Wishing to do what is right; diligent.",
  "Demanding": "Requiring much effort or attention.",
  "Exacting": "Making great demands on skill or attention.",
  "Fastidious": "Very attentive to detail.",
  "Meticulous": "Showing great attention to detail.",
  "Punctilious": "Strictly attentive to detail or rules.",
  "Scrupulous": "Very careful and morally strict.",
  "Nice": "Hard to please; fastidious.",
  "Stickler": "One who insists on something strictly.",
  "Hard to Please": "Difficult to satisfy.",
  "Cursory": "Hasty and not thorough.",
  "Perfunctory": "Carried out with minimal effort.",
  "Summarily": "Done quickly without attention to detail.",
  "Superficially": "On the surface; lacking depth."
};
